// Generated by CIRCT firtool-1.75.0
module AccumulatorScale(	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:90:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:90:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:90:7]
  output        io_in_ready,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  input         io_in_valid,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  input  [15:0] io_in_bits_acc_read_resp_data_0_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  input  [15:0] io_in_bits_acc_read_resp_data_1_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  input         io_in_bits_acc_read_resp_fromDMA,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  input  [31:0] io_in_bits_acc_read_resp_scale_bits,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  input  [1:0]  io_in_bits_acc_read_resp_acc_bank_id,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  input         io_out_ready,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  output        io_out_valid,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  output [1:0]  io_out_bits_acc_bank_id,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
  output        io_out_bits_fromDMA	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorScale.scala:101:14]
);

  wire [32:0] _activated_data_e_scaled_in_to_rec_fn_1_io_out;	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:124:34]
  wire [32:0] _activated_data_e_scaled_in_to_rec_fn_io_out;	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:124:34]
  wire        activated_data_e_scaled_f_rec_rawIn_isZeroExpIn = io_in_bits_acc_read_resp_scale_bits[30:23] == 8'h0;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30]
  wire [4:0]  activated_data_e_scaled_f_rec_rawIn_normDist = io_in_bits_acc_read_resp_scale_bits[22] ? 5'h0 : io_in_bits_acc_read_resp_scale_bits[21] ? 5'h1 : io_in_bits_acc_read_resp_scale_bits[20] ? 5'h2 : io_in_bits_acc_read_resp_scale_bits[19] ? 5'h3 : io_in_bits_acc_read_resp_scale_bits[18] ? 5'h4 : io_in_bits_acc_read_resp_scale_bits[17] ? 5'h5 : io_in_bits_acc_read_resp_scale_bits[16] ? 5'h6 : io_in_bits_acc_read_resp_scale_bits[15] ? 5'h7 : io_in_bits_acc_read_resp_scale_bits[14] ? 5'h8 : io_in_bits_acc_read_resp_scale_bits[13] ? 5'h9 : io_in_bits_acc_read_resp_scale_bits[12] ? 5'hA : io_in_bits_acc_read_resp_scale_bits[11] ? 5'hB : io_in_bits_acc_read_resp_scale_bits[10] ? 5'hC : io_in_bits_acc_read_resp_scale_bits[9] ? 5'hD : io_in_bits_acc_read_resp_scale_bits[8] ? 5'hE : io_in_bits_acc_read_resp_scale_bits[7] ? 5'hF : io_in_bits_acc_read_resp_scale_bits[6] ? 5'h10 : io_in_bits_acc_read_resp_scale_bits[5] ? 5'h11 : io_in_bits_acc_read_resp_scale_bits[4] ? 5'h12 : io_in_bits_acc_read_resp_scale_bits[3] ? 5'h13 : io_in_bits_acc_read_resp_scale_bits[2] ? 5'h14 : io_in_bits_acc_read_resp_scale_bits[1] ? 5'h15 : 5'h16;	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:91:52, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [53:0] _activated_data_e_scaled_f_rec_rawIn_subnormFract_T = {31'h0, io_in_bits_acc_read_resp_scale_bits[22:0]} << activated_data_e_scaled_f_rec_rawIn_normDist;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :52:33, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [8:0]  _activated_data_e_scaled_f_rec_rawIn_adjustedExp_T_4 = (activated_data_e_scaled_f_rec_rawIn_isZeroExpIn ? {4'hF, ~activated_data_e_scaled_f_rec_rawIn_normDist} : {1'h0, io_in_bits_acc_read_resp_scale_bits[30:23]}) + {7'h20, activated_data_e_scaled_f_rec_rawIn_isZeroExpIn ? 2'h2 : 2'h1};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [2:0]  _activated_data_e_scaled_f_rec_T_1 = activated_data_e_scaled_f_rec_rawIn_isZeroExpIn & ~(|(io_in_bits_acc_read_resp_scale_bits[22:0])) ? 3'h0 : _activated_data_e_scaled_f_rec_rawIn_adjustedExp_T_4[8:6];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,50}]
  wire        activated_data_e_scaled_f_rec_rawIn_isZeroExpIn_1 = io_in_bits_acc_read_resp_scale_bits[30:23] == 8'h0;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30]
  wire [4:0]  activated_data_e_scaled_f_rec_rawIn_normDist_1 = io_in_bits_acc_read_resp_scale_bits[22] ? 5'h0 : io_in_bits_acc_read_resp_scale_bits[21] ? 5'h1 : io_in_bits_acc_read_resp_scale_bits[20] ? 5'h2 : io_in_bits_acc_read_resp_scale_bits[19] ? 5'h3 : io_in_bits_acc_read_resp_scale_bits[18] ? 5'h4 : io_in_bits_acc_read_resp_scale_bits[17] ? 5'h5 : io_in_bits_acc_read_resp_scale_bits[16] ? 5'h6 : io_in_bits_acc_read_resp_scale_bits[15] ? 5'h7 : io_in_bits_acc_read_resp_scale_bits[14] ? 5'h8 : io_in_bits_acc_read_resp_scale_bits[13] ? 5'h9 : io_in_bits_acc_read_resp_scale_bits[12] ? 5'hA : io_in_bits_acc_read_resp_scale_bits[11] ? 5'hB : io_in_bits_acc_read_resp_scale_bits[10] ? 5'hC : io_in_bits_acc_read_resp_scale_bits[9] ? 5'hD : io_in_bits_acc_read_resp_scale_bits[8] ? 5'hE : io_in_bits_acc_read_resp_scale_bits[7] ? 5'hF : io_in_bits_acc_read_resp_scale_bits[6] ? 5'h10 : io_in_bits_acc_read_resp_scale_bits[5] ? 5'h11 : io_in_bits_acc_read_resp_scale_bits[4] ? 5'h12 : io_in_bits_acc_read_resp_scale_bits[3] ? 5'h13 : io_in_bits_acc_read_resp_scale_bits[2] ? 5'h14 : io_in_bits_acc_read_resp_scale_bits[1] ? 5'h15 : 5'h16;	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:91:52, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [53:0] _activated_data_e_scaled_f_rec_rawIn_subnormFract_T_2 = {31'h0, io_in_bits_acc_read_resp_scale_bits[22:0]} << activated_data_e_scaled_f_rec_rawIn_normDist_1;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :52:33, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [8:0]  _activated_data_e_scaled_f_rec_rawIn_adjustedExp_T_9 = (activated_data_e_scaled_f_rec_rawIn_isZeroExpIn_1 ? {4'hF, ~activated_data_e_scaled_f_rec_rawIn_normDist_1} : {1'h0, io_in_bits_acc_read_resp_scale_bits[30:23]}) + {7'h20, activated_data_e_scaled_f_rec_rawIn_isZeroExpIn_1 ? 2'h2 : 2'h1};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [2:0]  _activated_data_e_scaled_f_rec_T_9 = activated_data_e_scaled_f_rec_rawIn_isZeroExpIn_1 & ~(|(io_in_bits_acc_read_resp_scale_bits[22:0])) ? 3'h0 : _activated_data_e_scaled_f_rec_rawIn_adjustedExp_T_9[8:6];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,50}]
  INToRecFN_i16_e8_s24 activated_data_e_scaled_in_to_rec_fn (	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:124:34]
    .io_in  (io_in_bits_acc_read_resp_data_0_0),
    .io_out (_activated_data_e_scaled_in_to_rec_fn_io_out)
  );	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:124:34]
  MulAddRecFN_e8_s24 activated_data_e_scaled_muladder (	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:132:30]
    .io_a   (_activated_data_e_scaled_in_to_rec_fn_io_out),	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:124:34]
    .io_b   ({io_in_bits_acc_read_resp_scale_bits[31], _activated_data_e_scaled_f_rec_T_1[2:1], _activated_data_e_scaled_f_rec_T_1[0] | (&(_activated_data_e_scaled_f_rec_rawIn_adjustedExp_T_4[8:7])) & (|(io_in_bits_acc_read_resp_scale_bits[22:0])), _activated_data_e_scaled_f_rec_rawIn_adjustedExp_T_4[5:0], activated_data_e_scaled_f_rec_rawIn_isZeroExpIn ? {_activated_data_e_scaled_f_rec_rawIn_subnormFract_T[21:0], 1'h0} : io_in_bits_acc_read_resp_scale_bits[22:0]}),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:44:18, :46:21, :48:30, :49:34, :52:{33,46,64}, :57:9, :61:{32,57}, :64:28, :70:33, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, :50:{23,41}]
    .io_out (/* unused */)
  );	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:132:30]
  INToRecFN_i16_e8_s24 activated_data_e_scaled_in_to_rec_fn_1 (	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:124:34]
    .io_in  (io_in_bits_acc_read_resp_data_1_0),
    .io_out (_activated_data_e_scaled_in_to_rec_fn_1_io_out)
  );	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:124:34]
  MulAddRecFN_e8_s24 activated_data_e_scaled_muladder_1 (	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:132:30]
    .io_a   (_activated_data_e_scaled_in_to_rec_fn_1_io_out),	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:124:34]
    .io_b   ({io_in_bits_acc_read_resp_scale_bits[31], _activated_data_e_scaled_f_rec_T_9[2:1], _activated_data_e_scaled_f_rec_T_9[0] | (&(_activated_data_e_scaled_f_rec_rawIn_adjustedExp_T_9[8:7])) & (|(io_in_bits_acc_read_resp_scale_bits[22:0])), _activated_data_e_scaled_f_rec_rawIn_adjustedExp_T_9[5:0], activated_data_e_scaled_f_rec_rawIn_isZeroExpIn_1 ? {_activated_data_e_scaled_f_rec_rawIn_subnormFract_T_2[21:0], 1'h0} : io_in_bits_acc_read_resp_scale_bits[22:0]}),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:44:18, :46:21, :48:30, :49:34, :52:{33,46,64}, :57:9, :61:{32,57}, :64:28, :70:33, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, :50:{23,41}]
    .io_out (/* unused */)
  );	// @[generators/gemmini/src/main/scala/gemmini/Configs.scala:132:30]
  Pipeline_1 pipe_out_p (	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:75:19]
    .clock                        (clock),
    .reset                        (reset),
    .io_in_ready                  (io_in_ready),
    .io_in_valid                  (io_in_valid),
    .io_in_bits_resp_fromDMA      (io_in_bits_acc_read_resp_fromDMA),
    .io_in_bits_resp_acc_bank_id  (io_in_bits_acc_read_resp_acc_bank_id),
    .io_out_ready                 (io_out_ready),
    .io_out_valid                 (io_out_valid),
    .io_out_bits_resp_fromDMA     (io_out_bits_fromDMA),
    .io_out_bits_resp_acc_bank_id (io_out_bits_acc_bank_id)
  );	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:75:19]
endmodule

