// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ExecuteController(	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
  output        io_cmd_ready,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  input         io_cmd_valid,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  input  [6:0]  io_cmd_bits_cmd_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  input  [63:0] io_cmd_bits_cmd_rs1,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  input  [63:0] io_cmd_bits_cmd_rs2,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  input  [2:0]  io_cmd_bits_rob_id_bits,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output [11:0] io_im2col_req_bits_addr_data,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output [7:0]  io_im2col_req_bits_ocol,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output [3:0]  io_im2col_req_bits_krow,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output [8:0]  io_im2col_req_bits_icol,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output [2:0]  io_im2col_req_bits_stride,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output [10:0] io_im2col_req_bits_row_turn,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output [7:0]  io_im2col_req_bits_kdim2,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output [3:0]  io_im2col_req_bits_row_left,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output        io_im2col_req_bits_start_inputting,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  input         io_srams_read_0_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output        io_srams_read_0_resp_ready,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  input         io_srams_read_0_resp_bits_fromDMA,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  input         io_srams_read_1_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output        io_srams_read_1_resp_ready,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  input         io_srams_read_1_resp_bits_fromDMA,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output        io_completed_valid,	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
  output [2:0]  io_completed_bits	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:17:14]
);

  wire             mesh_io_d_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:191:19, :873:21, :877:{21,36}]
  wire             mesh_io_b_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:190:19, :873:21, :876:{21,36}]
  wire             mesh_io_a_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:189:19, :873:21, :875:{21,36}]
  wire             start_inputting_b;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:532:26, :540:7]
  wire             start_inputting_a;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:532:26, :540:7]
  wire             start_inputting_d;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:532:26, :540:7]
  wire             _GEN;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:429:48, :430:11]
  wire             _GEN_0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:429:48, :430:11]
  wire             _GEN_1;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:429:48, :430:11]
  wire             _GEN_2;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:331:25, :429:48, :430:11]
  wire             _GEN_3;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:330:25, :429:48, :430:11]
  wire             _GEN_4;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:329:25, :429:48, :430:11]
  wire             _mesh_io_a_ready;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_b_ready;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_d_ready;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_req_ready;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_resp_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_resp_bits_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire [2:0]       _mesh_io_resp_bits_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_resp_bits_last;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_tags_in_progress_0_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_tags_in_progress_1_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_tags_in_progress_2_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_tags_in_progress_3_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_tags_in_progress_4_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_io_tags_in_progress_5_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  wire             _mesh_cntl_signals_q_io_enq_ready;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_a_bank;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_b_bank;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_d_bank;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_a_read_from_acc;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_b_read_from_acc;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_d_read_from_acc;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_a_garbage;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_b_garbage;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_d_garbage;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_accumulate_zeros;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_preload_zeros;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_a_fire;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_b_fire;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_d_fire;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire [1:0]       _mesh_cntl_signals_q_io_deq_bits_a_unpadded_cols;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire [1:0]       _mesh_cntl_signals_q_io_deq_bits_b_unpadded_cols;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire [1:0]       _mesh_cntl_signals_q_io_deq_bits_d_unpadded_cols;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire [1:0]       _mesh_cntl_signals_q_io_deq_bits_total_rows;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire [2:0]       _mesh_cntl_signals_q_io_deq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_dataflow;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_im2colling;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _mesh_cntl_signals_q_io_deq_bits_first;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  wire             _cmd_q_io_enq_ready;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _cmd_q_io_deq_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _cmd_q_io_deq_valid_1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _cmd_q_io_deq_valid_2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [6:0]       _cmd_q_io_deq_bits_0_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0]      _cmd_q_io_deq_bits_0_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0]      _cmd_q_io_deq_bits_0_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _cmd_q_io_deq_bits_0_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [2:0]       _cmd_q_io_deq_bits_0_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [6:0]       _cmd_q_io_deq_bits_1_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0]      _cmd_q_io_deq_bits_1_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0]      _cmd_q_io_deq_bits_1_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _cmd_q_io_deq_bits_1_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [2:0]       _cmd_q_io_deq_bits_1_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0]      _cmd_q_io_deq_bits_2_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0]      _cmd_q_io_deq_bits_2_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [2:0]       _cmd_q_io_deq_bits_2_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _unrolled_cmd_mod_io_out_valid;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
  wire [6:0]       _unrolled_cmd_mod_io_out_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
  wire [63:0]      _unrolled_cmd_mod_io_out_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
  wire [63:0]      _unrolled_cmd_mod_io_out_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
  wire             _unrolled_cmd_mod_io_out_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
  wire [2:0]       _unrolled_cmd_mod_io_out_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
  reg  [1:0]       control_state;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:74:30]
  wire             DoConfig = _cmd_q_io_deq_bits_0_cmd_inst_funct == 7'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:83:28, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             in_prop = _cmd_q_io_deq_bits_0_cmd_inst_funct == 7'h4;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:84:38, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             DoComputes_0 = in_prop | _cmd_q_io_deq_bits_0_cmd_inst_funct == 7'h5;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:84:{38,63,68}, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  reg  [7:0]       ocol;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:97:21]
  reg  [3:0]       krow;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:99:21]
  reg  [2:0]       weight_stride;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:100:30]
  reg  [10:0]      row_turn;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:102:25]
  reg  [3:0]       row_left;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:103:25]
  reg  [7:0]       kdim2;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:104:22]
  reg  [3:0]       in_shift;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:116:21]
  reg              a_transpose;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:119:24]
  reg              bd_transpose;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:120:25]
  reg              config_initialized;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:121:35]
  wire             _b_address_place_T = _cmd_q_io_deq_bits_0_cmd_inst_funct == 7'h6;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:85:33, :87:30, :124:47, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [1:0]       a_address_place = _b_address_place_T ? 2'h1 : {a_transpose, 1'h0};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:85:33, :87:30, :119:24, :124:{28,47,64}]
  wire [3:0][63:0] _GEN_5 = {{_cmd_q_io_deq_bits_0_cmd_rs1}, {_cmd_q_io_deq_bits_2_cmd_rs1}, {_cmd_q_io_deq_bits_1_cmd_rs1}, {_cmd_q_io_deq_bits_0_cmd_rs1}};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:139:53, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [3:0][63:0] _GEN_6 = {{_cmd_q_io_deq_bits_0_cmd_rs2}, {_cmd_q_io_deq_bits_2_cmd_rs2}, {_cmd_q_io_deq_bits_1_cmd_rs2}, {_cmd_q_io_deq_bits_0_cmd_rs2}};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0]      _GEN_7 = _GEN_6[{1'h0, _b_address_place_T}];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:85:33, :87:30, :124:47, :127:28, :140:53]
  wire [1:0]       _GEN_8 = {1'h0, _cmd_q_io_deq_bits_0_cmd_inst_funct != 7'h6};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:85:33, :87:30, :141:55, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _a_garbage_T = _GEN_5[a_address_place][31] & _GEN_5[a_address_place][30];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:124:28, :139:53, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:48]
  wire             multiply_garbage = _a_garbage_T & _GEN_5[a_address_place][29] & (&(_GEN_5[a_address_place][11:0])) & _GEN_5[a_address_place][12];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:124:28, :139:53, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
  wire             _b_garbage_T = _GEN_7[31] & _GEN_7[30];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:48]
  wire             accumulate_zeros = _b_garbage_T & _GEN_7[29] & (&(_GEN_7[11:0])) & _GEN_7[12];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
  wire             _d_garbage_T = _GEN_5[_GEN_8][31] & _GEN_5[_GEN_8][30];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:139:53, :141:55, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:48]
  wire             preload_zeros = _d_garbage_T & _GEN_5[_GEN_8][29] & (&(_GEN_5[_GEN_8][11:0])) & _GEN_5[_GEN_8][12];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:139:53, :141:55, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
  reg              pending_completed_rob_ids_0_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38]
  reg  [2:0]       pending_completed_rob_ids_0_bits;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38]
  reg              pending_completed_rob_ids_1_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38]
  reg  [2:0]       pending_completed_rob_ids_1_bits;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38]
  wire             _mesh_io_req_bits_flush_T = control_state == 2'h2;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:74:30, :192:38]
  wire             matmul_in_progress = _mesh_io_tags_in_progress_0_rob_id_valid | _mesh_io_tags_in_progress_1_rob_id_valid | _mesh_io_tags_in_progress_2_rob_id_valid | _mesh_io_tags_in_progress_3_rob_id_valid | _mesh_io_tags_in_progress_4_rob_id_valid | _mesh_io_tags_in_progress_5_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20, :230:82]
  reg              a_fire_counter;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:236:27]
  reg              b_fire_counter;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:237:27]
  reg              d_fire_counter;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:238:27]
  reg              a_fire_started;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:240:31]
  reg              d_fire_started;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:241:31]
  reg              b_fire_started;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:242:31]
  reg  [16:0]      a_addr_offset;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:245:26]
  reg  [15:0]      a_addr_stride;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:246:26]
  wire [11:0]      _a_address_result_data_T = _GEN_5[a_address_place][11:0] + a_addr_offset[11:0];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:124:28, :139:53, :245:26, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:51:25]
  wire [11:0]      _b_address_result_data_T = _GEN_7[11:0] + {11'h0, b_fire_counter};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :237:27, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:51:25]
  wire [2:0]       _GEN_9 = {2'h0, d_fire_counter};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:238:27, :253:55]
  wire [1:0]       _GEN_10 = {1'h0, d_fire_counter};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:238:27, :253:55]
  wire [11:0]      _d_address_result_data_T = _GEN_5[_GEN_8][11:0] + {10'h0, 2'h1 - _GEN_10};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:139:53, :141:55, :253:55, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:51:25]
  wire             d_garbage = _d_garbage_T & _GEN_5[_GEN_8][29] & (&(_GEN_5[_GEN_8][11:0])) & _GEN_5[_GEN_8][12] | ~start_inputting_d;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:139:53, :141:55, :274:{46,49}, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
  reg              perform_single_preload;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:277:39]
  reg              perform_single_mul;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:278:35]
  reg              perform_mul_pre;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:279:32]
  wire             _performing_mul_pre_T = control_state == 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:74:30, :281:84]
  wire [2:0]       total_rows = d_garbage & ~a_transpose & ~bd_transpose ? 3'h4 : 3'h2;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :120:25, :274:46, :285:28, :288:60, :289:{5,74,77,111}, :301:16]
  wire             a_row_is_not_all_zeros = {1'h0, a_fire_counter} < (a_transpose ? _GEN_5[a_address_place][33:32] : _GEN_5[a_address_place][49:48]);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:119:24, :124:28, :139:53, :154:45, :155:45, :162:19, :236:27, :310:47]
  wire             b_row_is_not_all_zeros = {1'h0, b_fire_counter} < _GEN_7[49:48];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :157:45, :237:27, :311:47]
  wire             d_row_is_not_all_zeros = 2'h1 - _GEN_10 < (bd_transpose ? _GEN_5[_GEN_8][33:32] : _GEN_5[_GEN_8][49:48]);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:120:25, :139:53, :141:55, :158:47, :159:47, :166:19, :253:55, :312:{51,68}]
  wire             _GEN_11 = _a_garbage_T & _GEN_5[a_address_place][29] & (&(_GEN_5[a_address_place][11:0])) & _GEN_5[a_address_place][12];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:124:28, :139:53, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
  wire             _GEN_12 = _b_garbage_T & _GEN_7[29] & (&(_GEN_7[11:0])) & _GEN_7[12];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
  wire             _GEN_13 = _d_garbage_T & _GEN_5[_GEN_8][29] & (&(_GEN_5[_GEN_8][11:0])) & _GEN_5[_GEN_8][12];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:139:53, :141:55, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
  wire [2:0]       _about_to_fire_all_rows_T_13 = total_rows - 3'h1;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:285:28, :289:111, :301:16, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28]
  wire             _b_fire_counter_T_6 = b_fire_counter - 1'h1;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:237:27, generators/gemmini/src/main/scala/gemmini/Util.scala:27:15]
  wire [2:0]       _GEN_14 = {2'h0, b_fire_counter};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:237:27, generators/gemmini/src/main/scala/gemmini/Util.scala:30:10]
  wire [2:0]       _GEN_15 = {2'h0, _b_fire_counter_T_6};	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:27:15, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [2:0]       _GEN_16 = {2'h0, a_fire_counter};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:236:27, :347:56]
  wire             _d_fire_counter_T_6 = d_fire_counter - 1'h1;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:238:27, generators/gemmini/src/main/scala/gemmini/Util.scala:27:15]
  wire [2:0]       _GEN_17 = {2'h0, _d_fire_counter_T_6};	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:27:15, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire             _GEN_18 = a_fire_started & _GEN_16 == (_about_to_fire_all_rows_T_13 == 3'h0 ? 3'h0 : _GEN_14 >= total_rows - 3'h1 ? 3'h1 - (_about_to_fire_all_rows_T_13 - _GEN_14) - 3'h1 : _GEN_15) | a_fire_started & _GEN_16 == (_about_to_fire_all_rows_T_13 == 3'h0 ? 3'h0 : _GEN_9 >= total_rows - 3'h1 ? 3'h1 - (_about_to_fire_all_rows_T_13 - _GEN_9) - 3'h1 : _GEN_17);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :240:31, :253:55, :285:28, :289:111, :301:16, :347:{45,56}, :356:29, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28, :19:28, :30:{10,17,21,47,54,59}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire             _a_fire_counter_T_6 = a_fire_counter - 1'h1;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:236:27, generators/gemmini/src/main/scala/gemmini/Util.scala:27:15]
  wire [2:0]       _GEN_19 = {2'h0, _a_fire_counter_T_6};	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:27:15, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire             _GEN_20 = ~(_GEN_11 | _GEN_12 | ~start_inputting_b | ~start_inputting_a) & (_GEN_5[a_address_place][31] & _GEN_7[31] | ~(_GEN_7[31]) & ~(_GEN_5[a_address_place][31]) & _b_address_result_data_T[11] == _a_address_result_data_T[11]) & a_fire_started == b_fire_started & a_fire_counter == b_fire_counter | b_fire_started & _GEN_14 == (_about_to_fire_all_rows_T_13 == 3'h0 ? 3'h0 : _GEN_16 >= total_rows - 3'h1 ? 3'h1 - (_about_to_fire_all_rows_T_13 - _GEN_16) - 3'h1 : _GEN_19) | b_fire_started & _GEN_14 == (_about_to_fire_all_rows_T_13 == 3'h0 ? 3'h0 : _GEN_9 >= total_rows - 3'h1 ? 3'h1 - (_about_to_fire_all_rows_T_13 - _GEN_9) - 3'h1 : _GEN_17);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :124:28, :139:53, :140:53, :236:27, :237:27, :240:31, :242:31, :253:55, :272:49, :273:49, :285:28, :289:111, :301:16, :320:{34,49}, :321:25, :325:{5,40,65,89}, :326:{8,29,32,53,72}, :345:{48,62,73}, :347:{45,56}, :353:{19,26}, :356:29, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :43:{62,83,96}, :51:25, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28, :19:28, :30:{10,17,21,47,54,59}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire             _GEN_21 = ~(_GEN_11 | _GEN_13 | ~start_inputting_d | ~start_inputting_a) & (_GEN_5[a_address_place][31] & _GEN_5[_GEN_8][31] | ~(_GEN_5[_GEN_8][31]) & ~(_GEN_5[a_address_place][31]) & _d_address_result_data_T[11] == _a_address_result_data_T[11]) & a_fire_started == d_fire_started & a_fire_counter == d_fire_counter | d_fire_started & _GEN_9 == (_about_to_fire_all_rows_T_13 == 3'h0 ? 3'h0 : _GEN_16 >= total_rows - 3'h1 ? 3'h1 - (_about_to_fire_all_rows_T_13 - _GEN_16) - 3'h1 : _GEN_19) | ~(_GEN_12 | _GEN_13 | ~start_inputting_d | ~start_inputting_b) & (_GEN_7[31] & _GEN_5[_GEN_8][31] | ~(_GEN_5[_GEN_8][31]) & ~(_GEN_7[31]) & _d_address_result_data_T[11] == _b_address_result_data_T[11]) & b_fire_started == d_fire_started & b_fire_counter == d_fire_counter | d_fire_started & _GEN_9 == (_about_to_fire_all_rows_T_13 == 3'h0 ? 3'h0 : _GEN_14 >= total_rows - 3'h1 ? 3'h1 - (_about_to_fire_all_rows_T_13 - _GEN_14) - 3'h1 : _GEN_15);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :124:28, :139:53, :140:53, :141:55, :236:27, :237:27, :238:27, :240:31, :241:31, :242:31, :253:55, :272:49, :273:49, :274:49, :285:28, :289:111, :301:16, :320:{34,49}, :321:25, :325:{5,40,65,89}, :326:{8,29,32,53,72}, :345:{48,62,73}, :347:{45,56}, :353:{19,26}, :356:29, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :43:{62,83,96}, :51:25, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28, :19:28, :30:{10,17,21,47,54,59}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire             a_fire = ~_GEN_18 & _GEN_1 & _GEN_4;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:329:25, :356:{5,29}, :359:24, :429:48, :430:11]
  wire             b_fire = ~_GEN_20 & _GEN_0 & _GEN_3;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:330:25, :353:26, :356:{5,29}, :360:24, :429:48, :430:11]
  wire             d_fire = ~_GEN_21 & _GEN & _GEN_2;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:331:25, :353:26, :356:{5,29}, :361:24, :429:48, :430:11]
  wire             about_to_fire_all_rows = (_GEN_16 == _about_to_fire_all_rows_T_13 & a_fire | ~a_fire_counter) & (_GEN_14 == _about_to_fire_all_rows_T_13 & b_fire | ~b_fire_counter) & (_GEN_9 == _about_to_fire_all_rows_T_13 & d_fire | ~d_fire_counter) & (a_fire_started | b_fire_started | d_fire_started) & _mesh_cntl_signals_q_io_enq_ready;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :236:27, :237:27, :238:27, :240:31, :241:31, :242:31, :253:55, :334:24, :347:56, :359:24, :360:24, :361:24, :405:{49,70,81,108}, :406:{22,43,54,81}, :407:{22,43,54,81}, :408:{21,39,58}, :429:48, :430:11, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28, :30:10]
  assign _GEN_4 = ~(~_GEN_18 & ~(_a_address_result_data_T[11]) & start_inputting_a & ~multiply_garbage & a_row_is_not_all_zeros & ~io_srams_read_0_req_ready);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:310:47, :329:25, :356:{5,29}, :424:{46,59,67,88,91,109}, :429:{16,19,48}, :430:11, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :43:{62,83,96}, :51:25]
  assign _GEN_3 = ~(~_GEN_20 & ~(_b_address_result_data_T[11]) & start_inputting_b & ~accumulate_zeros & b_row_is_not_all_zeros & ~io_srams_read_0_req_ready);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:311:47, :330:25, :353:26, :356:{5,29}, :425:{46,59,67,88,91,109}, :429:{16,19,48}, :430:11, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :43:{62,83,96}, :51:25]
  assign _GEN_2 = ~(~_GEN_21 & ~(_d_address_result_data_T[11]) & start_inputting_d & ~preload_zeros & d_row_is_not_all_zeros & ~io_srams_read_0_req_ready);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:312:68, :331:25, :353:26, :356:{5,29}, :426:{46,59,67,88,91,106}, :429:{16,19,48}, :430:11, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :43:{62,83,96}, :51:25]
  assign _GEN_1 = ~(~_GEN_18 & _a_address_result_data_T[11] & start_inputting_a & ~multiply_garbage & a_row_is_not_all_zeros & ~io_srams_read_1_req_ready);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:310:47, :356:{5,29}, :424:{46,67,88,91,109}, :429:{16,19,48}, :430:11, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :43:{62,83,96}, :51:25]
  assign _GEN_0 = ~(~_GEN_20 & _b_address_result_data_T[11] & start_inputting_b & ~accumulate_zeros & b_row_is_not_all_zeros & ~io_srams_read_1_req_ready);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:311:47, :353:26, :356:{5,29}, :425:{46,67,88,91,109}, :429:{16,19,48}, :430:11, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :43:{62,83,96}, :51:25]
  assign _GEN = ~(~_GEN_21 & _d_address_result_data_T[11] & start_inputting_d & ~preload_zeros & d_row_is_not_all_zeros & ~io_srams_read_1_req_ready);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:312:68, :353:26, :356:{5,29}, :426:{46,67,88,91,106}, :429:{16,19,48}, :430:11, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :43:{62,83,96}, :51:25]
  wire             _GEN_22 = control_state == 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:74:30, :532:26]
  wire             _GEN_23 = DoConfig & ~matmul_in_progress & ~(pending_completed_rob_ids_0_valid | pending_completed_rob_ids_1_valid);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:83:28, :175:38, :230:82, :541:{23,26,46,49,98}]
  wire             _GEN_24 = _cmd_q_io_deq_valid_0 & _GEN_23;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:97:21, :540:7, :541:{23,46,105}, :547:48, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _GEN_25 = _GEN_22 & _GEN_24;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:97:21, :532:26, :540:7, :541:105, :547:48]
  wire             _GEN_26 = _GEN_25 & _cmd_q_io_deq_bits_0_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:97:21, :171:22, :532:26, :540:7, :541:105, :547:48, :579:24, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _GEN_27 = _cmd_q_io_deq_bits_0_cmd_inst_funct == 7'h6 & _cmd_q_io_deq_valid_1;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:85:33, :585:33, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _GEN_28 = _GEN_22 & _cmd_q_io_deq_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:281:43, :532:26, :540:7, :541:105, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             performing_single_preload = _GEN_28 & ~_GEN_23 & _GEN_27 | perform_single_preload & _performing_mul_pre_T;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:277:39, :281:{43,67,84}, :532:26, :535:30, :540:7, :541:{23,46,105}, :585:{33,103}]
  wire             _GEN_29 = DoComputes_0 & _cmd_q_io_deq_valid_1 & _cmd_q_io_deq_bits_1_cmd_inst_funct == 7'h6 & (~(a_address_place[1]) | _cmd_q_io_deq_valid_2);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:84:63, :85:33, :124:28, :228:50, :600:{33,49,66,70,96}, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _GEN_30 = _GEN_23 | _GEN_27;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:536:23, :541:{23,46,105}, :585:{33,103}, :601:9]
  wire             performing_mul_pre = _GEN_28 & ~_GEN_30 & _GEN_29 | perform_mul_pre & _performing_mul_pre_T;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:279:32, :281:{43,84}, :283:{36,53}, :532:26, :536:23, :540:7, :541:105, :585:103, :600:{33,49,66}, :601:9]
  wire             _GEN_31 = _GEN_23 | _GEN_27 | _GEN_29;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:537:26, :541:{23,46,105}, :585:{33,103}, :600:{33,49,66}, :601:9, :613:34]
  wire             performing_single_mul = _GEN_28 & ~_GEN_31 & DoComputes_0 | perform_single_mul & _performing_mul_pre_T;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:84:63, :278:35, :281:{43,84}, :282:{39,59}, :532:26, :537:26, :540:7, :541:105, :585:103, :601:9, :613:34]
  assign start_inputting_d = _GEN_22 ? _cmd_q_io_deq_valid_0 & ~_GEN_23 & (_GEN_27 | _GEN_29) : _performing_mul_pre_T & (perform_single_preload | perform_mul_pre);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:269:35, :277:39, :279:32, :281:84, :532:26, :535:30, :540:7, :541:{23,46,105}, :585:{33,103}, :594:29, :600:{33,49,66}, :601:9, :634:36, :637:27, :652:34, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  assign start_inputting_a = _GEN_22 ? _cmd_q_io_deq_valid_0 & ~_GEN_23 & (_GEN_27 ? a_transpose : _GEN_29 | DoComputes_0 & ~a_transpose) : _performing_mul_pre_T & (perform_single_preload ? a_transpose : perform_mul_pre | perform_single_mul & ~a_transpose);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:84:63, :119:24, :267:35, :277:39, :278:35, :279:32, :281:84, :289:5, :532:26, :535:30, :540:7, :541:{23,46,105}, :585:{33,103}, :592:29, :600:{33,49,66}, :601:9, :605:29, :613:34, :617:29, :634:36, :635:27, :652:34, :653:27, :671:37, :672:27, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _GEN_32 = perform_mul_pre | perform_single_mul;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:278:35, :279:32, :652:34, :654:27, :671:37]
  assign start_inputting_b = _GEN_22 ? _cmd_q_io_deq_valid_0 & ~_GEN_30 & (_GEN_29 | DoComputes_0) : _performing_mul_pre_T & ~perform_single_preload & _GEN_32;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:84:63, :268:35, :277:39, :281:84, :532:26, :536:23, :540:7, :541:105, :585:103, :593:29, :600:{33,49,66}, :601:9, :606:29, :613:34, :634:36, :636:27, :652:34, :654:27, :671:37, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [3:0][2:0]  _GEN_33 = {{_cmd_q_io_deq_bits_0_rob_id_bits}, {_cmd_q_io_deq_bits_2_rob_id_bits}, {_cmd_q_io_deq_bits_1_rob_id_bits}, {_cmd_q_io_deq_bits_0_rob_id_bits}};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:793:47, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _mesh_cntl_signals_q_io_deq_ready_T_1 = _mesh_io_a_ready & mesh_io_a_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20, :189:19, :873:21, :875:{21,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _mesh_cntl_signals_q_io_deq_ready_T_6 = _mesh_io_b_ready & mesh_io_b_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20, :190:19, :873:21, :876:{21,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _mesh_cntl_signals_q_io_deq_ready_T_12 = _mesh_io_d_ready & mesh_io_d_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20, :191:19, :873:21, :877:{21,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             mesh_cntl_signals_q_io_deq_ready = (~_mesh_cntl_signals_q_io_deq_bits_a_fire | _mesh_cntl_signals_q_io_deq_ready_T_1 | ~_mesh_io_a_ready) & (~_mesh_cntl_signals_q_io_deq_bits_b_fire | _mesh_cntl_signals_q_io_deq_ready_T_6 | ~_mesh_io_b_ready) & (~_mesh_cntl_signals_q_io_deq_bits_d_fire | _mesh_cntl_signals_q_io_deq_ready_T_12 | ~_mesh_io_d_ready) & (~_mesh_cntl_signals_q_io_deq_bits_first | _mesh_io_req_ready);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :186:20, :811:{40,53,71,74,92}, :812:{6,19,37,40,58}, :813:{6,19,37,40,58}, :814:{6,18}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _mesh_io_req_valid_T_1 = mesh_cntl_signals_q_io_deq_ready & _mesh_cntl_signals_q_io_deq_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :811:92, :812:58, :813:58, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _GEN_34 = _mesh_cntl_signals_q_io_deq_ready_T_1 & ~_mesh_cntl_signals_q_io_deq_bits_a_garbage & (|_mesh_cntl_signals_q_io_deq_bits_a_unpadded_cols) & ~_mesh_cntl_signals_q_io_deq_bits_im2colling;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :842:{23,41,44,60,84,90,93}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _GEN_35 = _mesh_cntl_signals_q_io_deq_bits_a_bank ? io_srams_read_1_resp_bits_fromDMA : io_srams_read_0_resp_bits_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :846:50]
  wire             _GEN_36 = _mesh_cntl_signals_q_io_deq_ready_T_6 & ~_mesh_cntl_signals_q_io_deq_bits_b_garbage & ~_mesh_cntl_signals_q_io_deq_bits_accumulate_zeros & (|_mesh_cntl_signals_q_io_deq_bits_b_unpadded_cols);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :850:{23,41,44,60,63,86,110}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _GEN_37 = _mesh_cntl_signals_q_io_deq_bits_b_bank ? io_srams_read_1_resp_bits_fromDMA : io_srams_read_0_resp_bits_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :854:50]
  wire             _GEN_38 = _mesh_cntl_signals_q_io_deq_ready_T_12 & ~_mesh_cntl_signals_q_io_deq_bits_d_garbage & ~_mesh_cntl_signals_q_io_deq_bits_preload_zeros & (|_mesh_cntl_signals_q_io_deq_bits_d_unpadded_cols);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :858:{23,41,44,60,63,83,107}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _GEN_39 = _mesh_cntl_signals_q_io_deq_bits_d_bank ? io_srams_read_1_resp_bits_fromDMA : io_srams_read_0_resp_bits_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :862:50]
  assign mesh_io_a_valid = _mesh_cntl_signals_q_io_deq_valid & _mesh_cntl_signals_q_io_deq_bits_a_fire & (_mesh_cntl_signals_q_io_deq_bits_a_garbage | _mesh_cntl_signals_q_io_deq_bits_a_unpadded_cols == 2'h0);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :189:19, :816:{36,60}, :873:21, :875:{21,36}]
  assign mesh_io_b_valid = _mesh_cntl_signals_q_io_deq_valid & _mesh_cntl_signals_q_io_deq_bits_b_fire & (_mesh_cntl_signals_q_io_deq_bits_b_garbage | _mesh_cntl_signals_q_io_deq_bits_b_unpadded_cols == 2'h0);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :190:19, :818:{36,60}, :873:21, :876:{21,36}]
  assign mesh_io_d_valid = _mesh_cntl_signals_q_io_deq_valid & _mesh_cntl_signals_q_io_deq_bits_d_fire & (_mesh_cntl_signals_q_io_deq_bits_d_garbage | _mesh_cntl_signals_q_io_deq_bits_d_unpadded_cols == 2'h0);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :191:19, :822:{36,60}, :873:21, :877:{21,36}]
  wire             mesh_io_req_valid = _mesh_cntl_signals_q_io_deq_valid ? _mesh_io_req_valid_T_1 & (_mesh_cntl_signals_q_io_deq_bits_a_fire | _mesh_cntl_signals_q_io_deq_bits_b_fire | _mesh_cntl_signals_q_io_deq_bits_d_fire) : _mesh_io_req_bits_flush_T;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :192:{21,38}, :873:21, :883:{23,58,74,89}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _GEN_40 = _mesh_io_resp_valid & _mesh_io_resp_bits_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20, :970:26]
  `ifndef SYNTHESIS	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:131:9]
    wire [1:0] _GEN_41 = {1'h0, a_transpose} + {1'h0, bd_transpose};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:119:24, :120:25, :126:79, :132:{38,73}]
    always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:131:9]
      if (~reset & config_initialized & _GEN_41[1]) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:121:35, :126:79, :131:{9,31}, :132:{38,73,109}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:131:9]
          $error("Assertion failed: Too many inputs are being fed into the single transposer we have\n    at ExecuteController.scala:131 assert(!(config_initialized &&\n");	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:131:9]
        if (`STOP_COND_)	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:131:9]
          $fatal;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:131:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire             mesh_completed_rob_id_fire = _GEN_40 & _mesh_io_resp_bits_last;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20, :966:44, :970:{26,65}, :974:16]
  wire             _GEN_42 = _GEN_40 & _mesh_io_resp_bits_last;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20, :532:26, :970:{26,65}, :974:16, :976:26]
  wire [2:0]       _GEN_43 = _GEN_42 ? _mesh_io_resp_bits_tag_rob_id_bits : _cmd_q_io_deq_bits_0_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20, :532:26, :970:65, :974:16, :976:26, :977:25, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             firing = start_inputting_a | start_inputting_b | start_inputting_d;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:363:{34,55}, :532:26, :540:7]
  wire             _GEN_44 = firing & a_fire & _mesh_cntl_signals_q_io_enq_ready;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :359:24, :363:{34,55}, :368:{22,32}, :429:48, :430:11]
  wire             _GEN_45 = firing & b_fire & _mesh_cntl_signals_q_io_enq_ready;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :360:24, :363:{34,55}, :376:{22,32}, :429:48, :430:11]
  wire             _GEN_46 = firing & d_fire & _mesh_cntl_signals_q_io_enq_ready;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :361:24, :363:{34,55}, :383:{22,32}, :429:48, :430:11]
  wire             _GEN_47 = _cmd_q_io_deq_bits_0_cmd_rs1[1:0] == 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:545:40, :547:33, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _GEN_48 = _GEN_22 & _cmd_q_io_deq_valid_0 & _GEN_23 & _GEN_47;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:246:26, :532:26, :540:7, :541:{23,46,105}, :547:{33,48}, :564:27, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire             _GEN_49 = _GEN_22 | ~_performing_mul_pre_T | perform_single_preload | ~(perform_mul_pre & about_to_fire_all_rows);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38, :277:39, :279:32, :281:84, :405:108, :406:81, :407:81, :408:58, :532:26, :634:36, :652:34, :657:38, :662:46]
  wire             _GEN_50 = perform_single_preload | perform_mul_pre | perform_single_mul;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:74:30, :277:39, :278:35, :279:32, :634:36, :639:38, :641:25, :652:34, :657:38, :671:37, :675:38, :677:25]
  wire [3:0][1:0]  _GEN_51 = {{(&control_state) & _mesh_io_req_ready ? 2'h0 : control_state}, {_mesh_io_req_ready & mesh_io_req_valid ? 2'h3 : control_state}, {_GEN_50 & about_to_fire_all_rows ? 2'h0 : control_state}, {~_cmd_q_io_deq_valid_0 | _GEN_23 ? control_state : _GEN_27 | _GEN_29 | DoComputes_0 ? 2'h1 : matmul_in_progress & DoConfig ? 2'h2 : control_state}};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:74:30, :83:28, :84:63, :186:20, :192:{21,38}, :230:82, :281:84, :405:108, :406:81, :407:81, :408:58, :532:26, :540:7, :541:{23,46,105}, :585:{33,103}, :596:25, :600:{33,49,66}, :601:9, :609:25, :613:34, :620:25, :624:{38,94}, :625:25, :627:79, :634:36, :639:38, :641:25, :652:34, :657:38, :671:37, :675:38, :677:25, :683:30, :684:23, :688:31, :690:23, :873:21, :883:23, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
    if (reset) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
      control_state <= 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:74:30]
      ocol <= 8'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:97:21]
      krow <= 4'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:99:21]
      weight_stride <= 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :100:30]
      row_turn <= 11'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:102:25]
      row_left <= 4'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:103:25]
      kdim2 <= 8'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:104:22]
      config_initialized <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:121:35]
      pending_completed_rob_ids_1_valid <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38]
      a_fire_started <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:240:31]
      d_fire_started <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:241:31]
      b_fire_started <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:242:31]
      perform_single_preload <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:277:39]
      perform_single_mul <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:278:35]
      perform_mul_pre <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:279:32]
    end
    else begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
      control_state <= _GEN_51[control_state];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:74:30, :192:38, :281:84, :532:26, :540:7, :634:36, :683:30]
      if (~_GEN_25 | _GEN_47) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:97:21, :104:22, :532:26, :540:7, :541:105, :547:{33,48}]
      end
      else begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:104:22, :532:26, :540:7, :541:105, :547:48]
        ocol <= _cmd_q_io_deq_bits_0_cmd_rs2[63:56];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:97:21, :568:40, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
        krow <= _cmd_q_io_deq_bits_0_cmd_rs2[47:44];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:99:21, :570:40, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
        weight_stride <= _cmd_q_io_deq_bits_0_cmd_rs2[22:20];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:100:30, :572:49, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
        row_turn <= _cmd_q_io_deq_bits_0_cmd_rs1[52:42];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:102:25, :576:{22,44}, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
        row_left <= _cmd_q_io_deq_bits_0_cmd_rs1[57:54];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:103:25, :575:44, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
        kdim2 <= _cmd_q_io_deq_bits_0_cmd_rs2[55:48];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:104:22, :569:41, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
      end
      config_initialized <= _GEN_48 | config_initialized;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:121:35, :246:26, :532:26, :540:7, :541:105, :547:48, :564:27, :566:32]
      pending_completed_rob_ids_1_valid <= (mesh_completed_rob_id_fire | pending_completed_rob_ids_0_valid | ~pending_completed_rob_ids_1_valid) & (_GEN_49 ? pending_completed_rob_ids_1_valid : _cmd_q_io_deq_bits_1_rob_id_valid & _GEN_6[_GEN_8][31] & _GEN_6[_GEN_8][30] & _GEN_6[_GEN_8][29] & (&(_GEN_6[_GEN_8][11:0])) & _GEN_6[_GEN_8][12]);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55, :175:38, :532:26, :634:36, :652:34, :662:74, :966:44, :970:65, :974:16, :982:38, :983:46, :986:52, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/Util.scala:139:13]
      a_fire_started <= ~about_to_fire_all_rows & (_GEN_44 | a_fire_started);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:240:31, :365:18, :368:{22,32,47}, :405:108, :406:81, :407:81, :408:58, :411:33, :412:20]
      d_fire_started <= ~about_to_fire_all_rows & (_GEN_46 | d_fire_started);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:241:31, :365:18, :381:18, :383:{22,32,47}, :405:108, :406:81, :407:81, :408:58, :411:33, :412:20, :414:20]
      b_fire_started <= ~about_to_fire_all_rows & (_GEN_45 | b_fire_started);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:242:31, :365:18, :374:18, :376:{22,32,47}, :405:108, :406:81, :407:81, :408:58, :411:33, :412:20, :413:20]
      if (_GEN_22) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:532:26]
        perform_single_preload <= _cmd_q_io_deq_valid_0 & ~_GEN_23 & _GEN_27;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:277:39, :535:30, :540:7, :541:{23,46,105}, :585:{33,103}, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
        perform_single_mul <= _cmd_q_io_deq_valid_0 & ~_GEN_31 & DoComputes_0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:84:63, :278:35, :537:26, :540:7, :541:105, :585:103, :601:9, :613:34, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
        perform_mul_pre <= _cmd_q_io_deq_valid_0 & ~_GEN_30 & _GEN_29;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:279:32, :536:23, :540:7, :541:105, :585:103, :600:{33,49,66}, :601:9, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
      end
    end
    if (_GEN_22 & _cmd_q_io_deq_valid_0 & _GEN_23 & _GEN_47 & ~(_cmd_q_io_deq_bits_0_cmd_rs1[7])) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:116:21, :532:26, :540:7, :541:{23,46,105}, :542:47, :547:{33,48}, :550:{19,38}, :554:24, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
      in_shift <= _cmd_q_io_deq_bits_0_cmd_rs2[3:0];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:116:21, :554:24, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
      a_transpose <= _cmd_q_io_deq_bits_0_cmd_rs1[8];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:119:24, :542:47, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
      bd_transpose <= _cmd_q_io_deq_bits_0_cmd_rs1[9];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:120:25, :542:47, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
    end
    pending_completed_rob_ids_0_valid <= ~(reset | ~mesh_completed_rob_id_fire & pending_completed_rob_ids_0_valid) & (_GEN_22 | ~_performing_mul_pre_T ? pending_completed_rob_ids_0_valid : perform_single_preload ? (about_to_fire_all_rows ? _cmd_q_io_deq_bits_0_rob_id_valid & _GEN_6[_GEN_8][31] & _GEN_6[_GEN_8][30] & _GEN_6[_GEN_8][29] & (&(_GEN_6[_GEN_8][11:0])) & _GEN_6[_GEN_8][12] : pending_completed_rob_ids_0_valid) : _GEN_32 & about_to_fire_all_rows ? _cmd_q_io_deq_bits_0_rob_id_valid : pending_completed_rob_ids_0_valid);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55, :175:38, :277:39, :281:84, :405:108, :406:81, :407:81, :408:58, :532:26, :634:36, :639:38, :643:{46,74}, :652:34, :654:27, :657:38, :661:40, :671:37, :675:38, :678:40, :966:44, :970:65, :974:16, :982:{9,38}, :983:46, :996:23, :998:47, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/Util.scala:139:13]
    if (_GEN_22 | ~(_performing_mul_pre_T & _GEN_50 & about_to_fire_all_rows)) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:74:30, :175:38, :281:84, :405:108, :406:81, :407:81, :408:58, :532:26, :634:36, :639:38, :641:25, :644:45, :652:34, :657:38, :671:37, :675:38, :677:25]
    end
    else	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38, :532:26]
      pending_completed_rob_ids_0_bits <= _cmd_q_io_deq_bits_0_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
    if (_GEN_49) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38, :532:26, :634:36, :652:34]
    end
    else	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38, :532:26, :634:36, :652:34]
      pending_completed_rob_ids_1_bits <= _cmd_q_io_deq_bits_1_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:175:38, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
    a_fire_counter <= firing & (_GEN_44 ? (|_about_to_fire_all_rows_T_13) & (_GEN_16 >= total_rows - 3'h1 ? 1'h1 - (_about_to_fire_all_rows_T_13[0] - a_fire_counter) - 1'h1 : _a_fire_counter_T_6) : a_fire_counter);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:236:27, :285:28, :289:111, :301:16, :347:56, :363:{34,55}, :365:18, :366:20, :368:{22,32,47}, :369:20, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28, :19:28, :27:15, :30:{10,17,21,47,54,59}, src/main/scala/chisel3/util/Mux.scala:126:16]
    b_fire_counter <= firing & (_GEN_45 ? (|_about_to_fire_all_rows_T_13) & (_GEN_14 >= total_rows - 3'h1 ? 1'h1 - (_about_to_fire_all_rows_T_13[0] - b_fire_counter) - 1'h1 : _b_fire_counter_T_6) : b_fire_counter);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:237:27, :285:28, :289:111, :301:16, :363:{34,55}, :374:18, :375:20, :376:{22,32,47}, :377:20, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28, :19:28, :27:15, :30:{10,17,21,47,54,59}, src/main/scala/chisel3/util/Mux.scala:126:16]
    d_fire_counter <= firing & (_GEN_46 ? (|_about_to_fire_all_rows_T_13) & (_GEN_9 >= total_rows - 3'h1 ? 1'h1 - (_about_to_fire_all_rows_T_13[0] - d_fire_counter) - 1'h1 : _d_fire_counter_T_6) : d_fire_counter);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:238:27, :253:55, :285:28, :289:111, :301:16, :363:{34,55}, :381:18, :382:20, :383:{22,32,47}, :384:20, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28, :19:28, :27:15, :30:{10,17,21,47,54,59}, src/main/scala/chisel3/util/Mux.scala:126:16]
    if (firing) begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:363:{34,55}]
      if (_GEN_44)	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:368:{22,32}]
        a_addr_offset <= _GEN_16 == _about_to_fire_all_rows_T_13 ? 17'h0 : a_addr_offset + {1'h0, a_addr_stride};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:245:26, :246:26, :347:56, :370:{25,41,82}, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28]
    end
    else	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:363:{34,55}]
      a_addr_offset <= 17'h0;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:245:26]
    if (_GEN_48)	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:246:26, :532:26, :540:7, :541:105, :547:48, :564:27]
      a_addr_stride <= _cmd_q_io_deq_bits_0_cmd_rs1[31:16];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:246:26, :542:47, generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:5];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
        control_state = _RANDOM[3'h0][1:0];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :74:30]
        ocol = _RANDOM[3'h0][10:3];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :74:30, :97:21]
        krow = _RANDOM[3'h0][22:19];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :74:30, :99:21]
        weight_stride = _RANDOM[3'h0][25:23];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :74:30, :100:30]
        row_turn = _RANDOM[3'h1][13:3];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :102:25]
        row_left = _RANDOM[3'h1][17:14];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :102:25, :103:25]
        kdim2 = _RANDOM[3'h1][25:18];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :102:25, :104:22]
        in_shift = _RANDOM[3'h1][31:28];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :102:25, :116:21]
        a_transpose = _RANDOM[3'h3][0];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24]
        bd_transpose = _RANDOM[3'h3][1];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :120:25]
        config_initialized = _RANDOM[3'h3][2];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :121:35]
        pending_completed_rob_ids_0_valid = _RANDOM[3'h3][3];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :175:38]
        pending_completed_rob_ids_0_bits = _RANDOM[3'h3][6:4];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :175:38]
        pending_completed_rob_ids_1_valid = _RANDOM[3'h3][7];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :175:38]
        pending_completed_rob_ids_1_bits = _RANDOM[3'h3][10:8];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :175:38]
        a_fire_counter = _RANDOM[3'h3][11];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :236:27]
        b_fire_counter = _RANDOM[3'h3][12];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :237:27]
        d_fire_counter = _RANDOM[3'h3][13];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :238:27]
        a_fire_started = _RANDOM[3'h3][14];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :240:31]
        d_fire_started = _RANDOM[3'h3][15];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :241:31]
        b_fire_started = _RANDOM[3'h3][16];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :242:31]
        a_addr_offset = {_RANDOM[3'h3][31:17], _RANDOM[3'h4][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :119:24, :245:26]
        a_addr_stride = _RANDOM[3'h4][17:2];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :245:26, :246:26]
        perform_single_preload = _RANDOM[3'h5][2];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :277:39]
        perform_single_mul = _RANDOM[3'h5][3];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :277:39, :278:35]
        perform_mul_pre = _RANDOM[3'h5][4];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :277:39, :279:32]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TransposePreloadUnroller unrolled_cmd_mod (	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_ready                (io_cmd_ready),
    .io_in_valid                (io_cmd_valid),
    .io_in_bits_cmd_inst_funct  (io_cmd_bits_cmd_inst_funct),
    .io_in_bits_cmd_rs1         (io_cmd_bits_cmd_rs1),
    .io_in_bits_cmd_rs2         (io_cmd_bits_cmd_rs2),
    .io_in_bits_rob_id_bits     (io_cmd_bits_rob_id_bits),
    .io_out_ready               (_cmd_q_io_enq_ready),	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
    .io_out_valid               (_unrolled_cmd_mod_io_out_valid),
    .io_out_bits_cmd_inst_funct (_unrolled_cmd_mod_io_out_bits_cmd_inst_funct),
    .io_out_bits_cmd_rs1        (_unrolled_cmd_mod_io_out_bits_cmd_rs1),
    .io_out_bits_cmd_rs2        (_unrolled_cmd_mod_io_out_bits_cmd_rs2),
    .io_out_bits_rob_id_valid   (_unrolled_cmd_mod_io_out_bits_rob_id_valid),
    .io_out_bits_rob_id_bits    (_unrolled_cmd_mod_io_out_bits_rob_id_bits)
  );	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
  MultiHeadedQueue_1 cmd_q (	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (_cmd_q_io_enq_ready),
    .io_enq_valid                 (_unrolled_cmd_mod_io_out_valid),	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
    .io_enq_bits_cmd_inst_funct   (_unrolled_cmd_mod_io_out_bits_cmd_inst_funct),	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
    .io_enq_bits_cmd_rs1          (_unrolled_cmd_mod_io_out_bits_cmd_rs1),	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
    .io_enq_bits_cmd_rs2          (_unrolled_cmd_mod_io_out_bits_cmd_rs2),	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
    .io_enq_bits_rob_id_valid     (_unrolled_cmd_mod_io_out_bits_rob_id_valid),	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
    .io_enq_bits_rob_id_bits      (_unrolled_cmd_mod_io_out_bits_rob_id_bits),	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:88:21]
    .io_deq_valid_0               (_cmd_q_io_deq_valid_0),
    .io_deq_valid_1               (_cmd_q_io_deq_valid_1),
    .io_deq_valid_2               (_cmd_q_io_deq_valid_2),
    .io_deq_bits_0_cmd_inst_funct (_cmd_q_io_deq_bits_0_cmd_inst_funct),
    .io_deq_bits_0_cmd_rs1        (_cmd_q_io_deq_bits_0_cmd_rs1),
    .io_deq_bits_0_cmd_rs2        (_cmd_q_io_deq_bits_0_cmd_rs2),
    .io_deq_bits_0_rob_id_valid   (_cmd_q_io_deq_bits_0_rob_id_valid),
    .io_deq_bits_0_rob_id_bits    (_cmd_q_io_deq_bits_0_rob_id_bits),
    .io_deq_bits_1_cmd_inst_funct (_cmd_q_io_deq_bits_1_cmd_inst_funct),
    .io_deq_bits_1_cmd_rs1        (_cmd_q_io_deq_bits_1_cmd_rs1),
    .io_deq_bits_1_cmd_rs2        (_cmd_q_io_deq_bits_1_cmd_rs2),
    .io_deq_bits_1_rob_id_valid   (_cmd_q_io_deq_bits_1_rob_id_valid),
    .io_deq_bits_1_rob_id_bits    (_cmd_q_io_deq_bits_1_rob_id_bits),
    .io_deq_bits_2_cmd_rs1        (_cmd_q_io_deq_bits_2_cmd_rs1),
    .io_deq_bits_2_cmd_rs2        (_cmd_q_io_deq_bits_2_cmd_rs2),
    .io_deq_bits_2_rob_id_bits    (_cmd_q_io_deq_bits_2_rob_id_bits),
    .io_deq_pop                   (_GEN_22 ? {1'h0, _GEN_24} : _performing_mul_pre_T ? (perform_single_preload ? {1'h0, about_to_fire_all_rows} : perform_mul_pre ? {about_to_fire_all_rows, 1'h0} : {1'h0, perform_single_mul & about_to_fire_all_rows}) : 2'h0)	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:70:11, :97:21, :277:39, :278:35, :279:32, :281:84, :405:108, :406:81, :407:81, :408:58, :532:26, :540:7, :541:105, :547:48, :581:19, :634:36, :639:38, :640:19, :652:34, :657:38, :658:19, :671:37, :675:38, :676:19]
  );	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  Queue5_ComputeCntlSignals mesh_cntl_signals_q (	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
    .clock                                (clock),
    .reset                                (reset),
    .io_enq_ready                         (_mesh_cntl_signals_q_io_enq_ready),
    .io_enq_valid                         (performing_mul_pre | performing_single_mul | performing_single_preload),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:281:43, :282:39, :283:36, :532:26, :540:7, :541:105, :696:{38,63}]
    .io_enq_bits_perform_mul_pre          (performing_mul_pre),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:283:36, :532:26, :540:7, :541:105]
    .io_enq_bits_perform_single_mul       (performing_single_mul),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:282:39, :532:26, :540:7, :541:105]
    .io_enq_bits_perform_single_preload   (performing_single_preload),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:281:43, :532:26, :540:7, :541:105]
    .io_enq_bits_a_bank                   (_a_address_result_data_T[11]),	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :51:25]
    .io_enq_bits_b_bank                   (_b_address_result_data_T[11]),	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :51:25]
    .io_enq_bits_d_bank                   (_d_address_result_data_T[11]),	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:33:79, :51:25]
    .io_enq_bits_a_bank_acc               (_a_address_result_data_T[8]),	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:35:82, :51:25]
    .io_enq_bits_b_bank_acc               (_b_address_result_data_T[8]),	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:35:82, :51:25]
    .io_enq_bits_d_bank_acc               (_d_address_result_data_T[8]),	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:35:82, :51:25]
    .io_enq_bits_a_garbage                (_a_garbage_T & _GEN_5[a_address_place][29] & (&(_GEN_5[a_address_place][11:0])) & _GEN_5[a_address_place][12] | ~start_inputting_a),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:124:28, :139:53, :272:{46,49}, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
    .io_enq_bits_b_garbage                (_b_garbage_T & _GEN_7[29] & (&(_GEN_7[11:0])) & _GEN_7[12] | ~start_inputting_b),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :273:{46,49}, :532:26, :540:7, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
    .io_enq_bits_d_garbage                (d_garbage),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:274:46]
    .io_enq_bits_accumulate_zeros         (accumulate_zeros),	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{62,83,96}]
    .io_enq_bits_preload_zeros            (preload_zeros),	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{62,83,96}]
    .io_enq_bits_a_fire                   (a_fire),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:359:24, :429:48, :430:11]
    .io_enq_bits_b_fire                   (b_fire),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:360:24, :429:48, :430:11]
    .io_enq_bits_d_fire                   (d_fire),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:361:24, :429:48, :430:11]
    .io_enq_bits_a_unpadded_cols          (a_row_is_not_all_zeros ? (a_transpose ? _GEN_5[a_address_place][49:48] : _GEN_5[a_address_place][33:32]) : 2'h0),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:119:24, :124:28, :139:53, :154:45, :155:45, :161:19, :310:47, :775:57]
    .io_enq_bits_b_unpadded_cols          (b_row_is_not_all_zeros ? _GEN_7[33:32] : 2'h0),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :156:45, :311:47, :776:57]
    .io_enq_bits_d_unpadded_cols          (d_row_is_not_all_zeros ? (bd_transpose ? _GEN_5[_GEN_8][49:48] : _GEN_5[_GEN_8][33:32]) : 2'h0),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:120:25, :139:53, :141:55, :158:47, :159:47, :165:19, :312:68, :777:57]
    .io_enq_bits_c_addr_is_acc_addr       (_GEN_6[_GEN_8][31]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55]
    .io_enq_bits_c_addr_accumulate        (_GEN_6[_GEN_8][30]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55]
    .io_enq_bits_c_addr_read_full_acc_row (_GEN_6[_GEN_8][29]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55]
    .io_enq_bits_c_addr_norm_cmd          (_GEN_6[_GEN_8][28:26]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55]
    .io_enq_bits_c_addr_garbage           (_GEN_6[_GEN_8][25:13]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55]
    .io_enq_bits_c_addr_garbage_bit       (_GEN_6[_GEN_8][12]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55]
    .io_enq_bits_c_addr_data              (_GEN_6[_GEN_8][11:0]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55]
    .io_enq_bits_c_rows                   (_GEN_6[_GEN_8][49:48]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55, :168:39]
    .io_enq_bits_c_cols                   (_GEN_6[_GEN_8][33:32]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55, :167:39]
    .io_enq_bits_a_transpose              (a_transpose),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:119:24]
    .io_enq_bits_bd_transpose             (bd_transpose),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:120:25]
    .io_enq_bits_total_rows               (total_rows[1:0]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:285:28, :289:111, :301:16, :779:46]
    .io_enq_bits_rob_id_valid             (~performing_single_mul & ~(_GEN_6[_GEN_8][31] & _GEN_6[_GEN_8][30] & _GEN_6[_GEN_8][29] & (&(_GEN_6[_GEN_8][11:0])) & _GEN_6[_GEN_8][12])),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:140:53, :141:55, :142:55, :282:39, :532:26, :540:7, :541:105, :792:{51,74,77}, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:43:{48,62,83,91,96}]
    .io_enq_bits_rob_id_bits              (_GEN_33[_GEN_8]),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:141:55, :793:47]
    .io_enq_bits_prop                     (~performing_single_preload & in_prop),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:84:38, :281:43, :532:26, :540:7, :541:105, :796:46]
    .io_enq_bits_shift                    (in_shift),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:116:21]
    .io_enq_bits_first                    (~a_fire_started & ~b_fire_started & ~d_fire_started),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:240:31, :241:31, :242:31, :801:{44,60,63,79,82}]
    .io_deq_ready                         (mesh_cntl_signals_q_io_deq_ready),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:811:92, :812:58, :813:58]
    .io_deq_valid                         (_mesh_cntl_signals_q_io_deq_valid),
    .io_deq_bits_a_bank                   (_mesh_cntl_signals_q_io_deq_bits_a_bank),
    .io_deq_bits_b_bank                   (_mesh_cntl_signals_q_io_deq_bits_b_bank),
    .io_deq_bits_d_bank                   (_mesh_cntl_signals_q_io_deq_bits_d_bank),
    .io_deq_bits_a_read_from_acc          (_mesh_cntl_signals_q_io_deq_bits_a_read_from_acc),
    .io_deq_bits_b_read_from_acc          (_mesh_cntl_signals_q_io_deq_bits_b_read_from_acc),
    .io_deq_bits_d_read_from_acc          (_mesh_cntl_signals_q_io_deq_bits_d_read_from_acc),
    .io_deq_bits_a_garbage                (_mesh_cntl_signals_q_io_deq_bits_a_garbage),
    .io_deq_bits_b_garbage                (_mesh_cntl_signals_q_io_deq_bits_b_garbage),
    .io_deq_bits_d_garbage                (_mesh_cntl_signals_q_io_deq_bits_d_garbage),
    .io_deq_bits_accumulate_zeros         (_mesh_cntl_signals_q_io_deq_bits_accumulate_zeros),
    .io_deq_bits_preload_zeros            (_mesh_cntl_signals_q_io_deq_bits_preload_zeros),
    .io_deq_bits_a_fire                   (_mesh_cntl_signals_q_io_deq_bits_a_fire),
    .io_deq_bits_b_fire                   (_mesh_cntl_signals_q_io_deq_bits_b_fire),
    .io_deq_bits_d_fire                   (_mesh_cntl_signals_q_io_deq_bits_d_fire),
    .io_deq_bits_a_unpadded_cols          (_mesh_cntl_signals_q_io_deq_bits_a_unpadded_cols),
    .io_deq_bits_b_unpadded_cols          (_mesh_cntl_signals_q_io_deq_bits_b_unpadded_cols),
    .io_deq_bits_d_unpadded_cols          (_mesh_cntl_signals_q_io_deq_bits_d_unpadded_cols),
    .io_deq_bits_total_rows               (_mesh_cntl_signals_q_io_deq_bits_total_rows),
    .io_deq_bits_rob_id_valid             (_mesh_cntl_signals_q_io_deq_bits_rob_id_valid),
    .io_deq_bits_rob_id_bits              (_mesh_cntl_signals_q_io_deq_bits_rob_id_bits),
    .io_deq_bits_dataflow                 (_mesh_cntl_signals_q_io_deq_bits_dataflow),
    .io_deq_bits_im2colling               (_mesh_cntl_signals_q_io_deq_bits_im2colling),
    .io_deq_bits_first                    (_mesh_cntl_signals_q_io_deq_bits_first)
  );	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
  MeshWithDelays mesh (	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
    .clock                              (clock),
    .reset                              (reset),
    .io_a_ready                         (_mesh_io_a_ready),
    .io_a_valid                         (mesh_io_a_valid),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:189:19, :873:21, :875:{21,36}]
    .io_b_ready                         (_mesh_io_b_ready),
    .io_b_valid                         (mesh_io_b_valid),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:190:19, :873:21, :876:{21,36}]
    .io_d_ready                         (_mesh_io_d_ready),
    .io_d_valid                         (mesh_io_d_valid),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:191:19, :873:21, :877:{21,36}]
    .io_req_ready                       (_mesh_io_req_ready),
    .io_req_valid                       (mesh_io_req_valid),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:192:21, :873:21, :883:23]
    .io_req_bits_tag_rob_id_valid       (_mesh_cntl_signals_q_io_deq_bits_rob_id_valid),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
    .io_req_bits_tag_rob_id_bits        (_mesh_cntl_signals_q_io_deq_bits_rob_id_bits),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
    .io_req_bits_pe_control_dataflow    (_mesh_cntl_signals_q_io_deq_bits_dataflow),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35]
    .io_req_bits_total_rows             (_mesh_cntl_signals_q_io_deq_valid ? _mesh_cntl_signals_q_io_deq_bits_total_rows : 2'h2),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :200:31, :873:21, :887:33]
    .io_req_bits_flush                  ({1'h0, _mesh_io_req_bits_flush_T & ~_mesh_cntl_signals_q_io_deq_valid}),	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:178:35, :192:38, :207:{26,57,60}]
    .io_resp_valid                      (_mesh_io_resp_valid),
    .io_resp_bits_tag_rob_id_valid      (_mesh_io_resp_bits_tag_rob_id_valid),
    .io_resp_bits_tag_rob_id_bits       (_mesh_io_resp_bits_tag_rob_id_bits),
    .io_resp_bits_total_rows            (/* unused */),
    .io_resp_bits_last                  (_mesh_io_resp_bits_last),
    .io_tags_in_progress_0_rob_id_valid (_mesh_io_tags_in_progress_0_rob_id_valid),
    .io_tags_in_progress_1_rob_id_valid (_mesh_io_tags_in_progress_1_rob_id_valid),
    .io_tags_in_progress_2_rob_id_valid (_mesh_io_tags_in_progress_2_rob_id_valid),
    .io_tags_in_progress_3_rob_id_valid (_mesh_io_tags_in_progress_3_rob_id_valid),
    .io_tags_in_progress_4_rob_id_valid (_mesh_io_tags_in_progress_4_rob_id_valid),
    .io_tags_in_progress_5_rob_id_valid (_mesh_io_tags_in_progress_5_rob_id_valid)
  );	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:186:20]
  assign io_im2col_req_bits_addr_data = _GEN_5[a_address_place][11:0];	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :124:28, :139:53]
  assign io_im2col_req_bits_ocol = ocol;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :97:21]
  assign io_im2col_req_bits_krow = krow;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :99:21]
  assign io_im2col_req_bits_icol = {1'h0, ocol - 8'h1} * {6'h0, weight_stride} + {5'h0, krow};	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :97:21, :99:21, :100:30, :111:{18,25,41}]
  assign io_im2col_req_bits_stride = weight_stride;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :100:30]
  assign io_im2col_req_bits_row_turn = row_turn;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :102:25]
  assign io_im2col_req_bits_kdim2 = kdim2;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :104:22]
  assign io_im2col_req_bits_row_left = row_left;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :103:25]
  assign io_im2col_req_bits_start_inputting = start_inputting_a;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :532:26, :540:7]
  assign io_srams_read_0_resp_ready = _mesh_io_req_valid_T_1 & (~_GEN_38 | _mesh_cntl_signals_q_io_deq_bits_d_read_from_acc | _mesh_cntl_signals_q_io_deq_bits_d_bank ? (~_GEN_36 | _mesh_cntl_signals_q_io_deq_bits_b_read_from_acc | _mesh_cntl_signals_q_io_deq_bits_b_bank ? _GEN_34 & ~_mesh_cntl_signals_q_io_deq_bits_a_read_from_acc & ~_mesh_cntl_signals_q_io_deq_bits_a_bank & ~_GEN_35 : ~_GEN_37) : ~_GEN_39);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :178:35, :453:33, :841:42, :842:{23,41,60,90,111}, :843:35, :846:{47,50}, :850:{23,41,60,86,117}, :851:35, :854:{47,50}, :858:{23,41,60,83,114}, :859:35, :862:{47,50}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_srams_read_1_resp_ready = _mesh_io_req_valid_T_1 & (~_GEN_38 | _mesh_cntl_signals_q_io_deq_bits_d_read_from_acc | ~_mesh_cntl_signals_q_io_deq_bits_d_bank ? (~_GEN_36 | _mesh_cntl_signals_q_io_deq_bits_b_read_from_acc | ~_mesh_cntl_signals_q_io_deq_bits_b_bank ? _GEN_34 & ~_mesh_cntl_signals_q_io_deq_bits_a_read_from_acc & _mesh_cntl_signals_q_io_deq_bits_a_bank & ~_GEN_35 : ~_GEN_37) : ~_GEN_39);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :178:35, :453:33, :841:42, :842:{23,41,60,90,111}, :843:35, :846:{47,50}, :850:{23,41,60,86,117}, :851:35, :854:{47,50}, :858:{23,41,60,83,114}, :859:35, :862:{47,50}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_completed_valid = mesh_completed_rob_id_fire ? _GEN_42 | _GEN_26 : pending_completed_rob_ids_0_valid | pending_completed_rob_ids_1_valid | _GEN_42 | _GEN_26;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :171:22, :175:38, :532:26, :540:7, :541:105, :579:24, :966:44, :970:65, :974:16, :976:26, :982:38, :983:46, :984:26, :986:52, :987:26]
  assign io_completed_bits = mesh_completed_rob_id_fire ? _GEN_43 : pending_completed_rob_ids_0_valid ? pending_completed_rob_ids_0_bits : pending_completed_rob_ids_1_valid ? pending_completed_rob_ids_1_bits : _GEN_43;	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:12:7, :175:38, :532:26, :966:44, :970:65, :974:16, :977:25, :982:38, :983:46, :985:25, :986:52, :988:25]
endmodule

