// Generated by CIRCT firtool-1.75.0
module RRArbiter_2(	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
  input         io_in_0_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  input  [7:0]  io_in_0_bits_data,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  input  [31:0] io_in_0_bits_scale_bits,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  input         io_in_0_bits_index,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  output        io_out_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  output [7:0]  io_out_bits_data,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  output [31:0] io_out_bits_scale_bits,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  output        io_out_bits_index	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
);

  assign io_out_valid = io_in_0_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
  assign io_out_bits_data = io_in_0_bits_data;	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
  assign io_out_bits_scale_bits = io_in_0_bits_scale_bits;	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
  assign io_out_bits_index = io_in_0_bits_index;	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
endmodule

