// Generated by CIRCT firtool-1.75.0
module Tile(	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:16:7]
  input  [2:0] io_in_id_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input        io_in_last_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output [2:0] io_out_id_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output       io_out_last_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input        io_in_valid_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output       io_out_valid_0	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
);

  PE_4 tile_0_0 (	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:42:44]
    .io_in_id     (io_in_id_0),
    .io_out_id    (io_out_id_0),
    .io_in_last   (io_in_last_0),
    .io_out_last  (io_out_last_0),
    .io_in_valid  (io_in_valid_0),
    .io_out_valid (io_out_valid_0)
  );	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:42:44]
endmodule

