// Generated by CIRCT firtool-1.75.0
module AccPipeShared(	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:73:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:73:7]
  input         io_in_sel_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  input         io_in_sel_1,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  input  [15:0] io_ina_0_0_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  input  [15:0] io_ina_0_1_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  input  [15:0] io_ina_1_0_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  input  [15:0] io_ina_1_1_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  input  [15:0] io_inb_0_0_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  input  [15:0] io_inb_0_1_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  input  [15:0] io_inb_1_0_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  input  [15:0] io_inb_1_1_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  output [15:0] io_out_0_0,	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
  output [15:0] io_out_1_0	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:74:14]
);

  AccPipe m (	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:84:21]
    .clock  (clock),
    .io_op1 ((io_in_sel_0 ? io_ina_0_0_0 : 16'h0) | (io_in_sel_1 ? io_ina_1_0_0 : 16'h0)),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_op2 ((io_in_sel_0 ? io_inb_0_0_0 : 16'h0) | (io_in_sel_1 ? io_inb_1_0_0 : 16'h0)),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_sum (io_out_0_0)
  );	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:84:21]
  AccPipe m_1 (	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:84:21]
    .clock  (clock),
    .io_op1 ((io_in_sel_0 ? io_ina_0_1_0 : 16'h0) | (io_in_sel_1 ? io_ina_1_1_0 : 16'h0)),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_op2 ((io_in_sel_0 ? io_inb_0_1_0 : 16'h0) | (io_in_sel_1 ? io_inb_1_1_0 : 16'h0)),	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_sum (io_out_1_0)
  );	// @[generators/gemmini/src/main/scala/gemmini/AccumulatorMem.scala:84:21]
endmodule

