// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BeatMerger(	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
  output        io_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input         io_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input  [1:0]  io_req_bits_shift,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input  [11:0] io_req_bits_addr,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input         io_req_bits_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input         io_req_bits_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input         io_req_bits_has_acc_bitwidth,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input  [15:0] io_req_bits_block_stride,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input  [4:0]  io_req_bits_spad_row_offset,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input  [1:0]  io_req_bits_lg_len_req,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input  [2:0]  io_req_bits_bytes_to_read,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_in_ready,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input         io_in_valid,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input  [7:0]  io_in_bits,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  input         io_out_ready,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_out_valid,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output [31:0] io_out_bits_data,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output [11:0] io_out_bits_addr,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_out_bits_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_out_bits_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_out_bits_has_acc_bitwidth,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_out_bits_mask_0,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_out_bits_mask_1,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_out_bits_mask_2,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_out_bits_mask_3,	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
  output        io_out_bits_last	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:33:14]
);

  wire         io_req_ready_0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:64:16, :98:22, :101:78, :103:20]
  reg          req_valid;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg  [1:0]   req_bits_shift;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg  [11:0]  req_bits_addr;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg          req_bits_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg          req_bits_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg          req_bits_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg  [15:0]  req_bits_block_stride;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg  [4:0]   req_bits_spad_row_offset;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg  [1:0]   req_bits_lg_len_req;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg  [2:0]   req_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
  reg  [31:0]  buffer;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:46:19]
  wire [2:0]   rowBytes = req_bits_has_acc_bitwidth ? 3'h4 : 3'h2;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16, :48:21]
  reg  [2:0]   bytesSent;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:50:22]
  reg  [2:0]   bytesRead;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:51:22]
  wire [2:0]   _GEN = {1'h0, req_bits_shift};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :52:43]
  wire [3:0]   _GEN_0 = {1'h0, bytesRead};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:51:22, :52:71]
  wire [2:0]   bytesReadAfterShift = bytesRead > _GEN ? bytesRead - _GEN : 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :51:22, :52:{32,43,71}]
  wire [2:0]   usefulBytesRead = bytesReadAfterShift < req_bits_bytes_to_read ? bytesReadAfterShift : req_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :52:32, generators/gemmini/src/main/scala/gemmini/Util.scala:109:{8,12}]
  wire         _spad_row_offset_T_3 = bytesSent == 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :50:22, :57:41]
  wire [5:0]   _bytesSent_next_T_4 = {3'h0, bytesSent} + {1'h0, {2'h0, rowBytes} - (_spad_row_offset_T_3 ? req_bits_spad_row_offset : 5'h0)};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16, :48:21, :50:22, :57:{30,41}, :58:32, generators/gemmini/src/main/scala/gemmini/Util.scala:35:11]
  wire [4:0]   _GEN_1 = {2'h0, req_bits_bytes_to_read};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, generators/gemmini/src/main/scala/gemmini/Util.scala:35:8]
  wire [4:0]   bytesSent_next = _bytesSent_next_T_4 > {3'h0, req_bits_bytes_to_read} ? _GEN_1 : _bytesSent_next_T_4[4:0];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16, generators/gemmini/src/main/scala/gemmini/Util.scala:35:{8,11,16,30}]
  wire         last_sending = bytesSent_next == _GEN_1;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:61:37, generators/gemmini/src/main/scala/gemmini/Util.scala:35:8]
  wire [3:0]   _io_in_ready_T_1 = 4'h1 << req_bits_lg_len_req;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :62:42]
  wire         _current_lg_len_req_T = io_req_ready_0 & io_req_valid;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:64:16, :98:22, :101:78, :103:20, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire         io_in_ready_0 = _current_lg_len_req_T | req_valid & _GEN_0 != _io_in_ready_T_1;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :52:71, :62:42, :66:{30,44,57}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire         io_out_valid_0 = req_valid & usefulBytesRead > bytesSent & (usefulBytesRead - bytesSent >= rowBytes | usefulBytesRead == req_bits_bytes_to_read);	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :48:21, :50:22, :68:{29,48,60,80,92,104}, :69:21, generators/gemmini/src/main/scala/gemmini/Util.scala:109:8]
  wire [542:0] _io_out_bits_data_T_5 = {511'h0, buffer >> {26'h0, bytesSent, 3'h0}} << (_spad_row_offset_T_3 ? {1'h0, req_bits_spad_row_offset, 3'h0} : 9'h0);	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16, :46:19, :50:22, :57:41, :70:{31,53,59,104}]
  wire [4:0]   spad_row_offset = _spad_row_offset_T_3 ? req_bits_spad_row_offset : 5'h0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :57:41, :72:30]
  wire [5:0]   _GEN_2 = {3'h0, req_bits_bytes_to_read - bytesSent};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16, :50:22, :74:{29,56}]
  wire [4:0]   spad_row_offset_1 = _spad_row_offset_T_3 ? req_bits_spad_row_offset : 5'h0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :57:41, :72:30]
  wire [5:0]   _GEN_3 = {1'h0, spad_row_offset_1} + _GEN_2;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:72:30, :74:29]
  wire [4:0]   spad_row_offset_2 = _spad_row_offset_T_3 ? req_bits_spad_row_offset : 5'h0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :57:41, :72:30]
  wire [4:0]   spad_row_offset_3 = _spad_row_offset_T_3 ? req_bits_spad_row_offset : 5'h0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :57:41, :72:30]
  wire [5:0]   _GEN_4 = {1'h0, spad_row_offset_3} + _GEN_2;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:72:30, :74:29]
  wire [4:0]   _io_out_bits_addr_total_bytes_sent_T = req_bits_spad_row_offset + {2'h0, bytesSent};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :50:22, :77:53, generators/gemmini/src/main/scala/gemmini/Util.scala:35:11]
  wire         _GEN_5 = _GEN_0 == _io_in_ready_T_1;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:52:71, :62:42, :93:19]
  wire         _GEN_6 = io_out_ready & io_out_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:68:{29,60}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire         _GEN_7 = last_sending & _GEN_5;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:61:37, :93:19, :101:24]
  assign io_req_ready_0 = _GEN_6 & _GEN_7 | ~req_valid;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :64:{16,19}, :98:22, :101:{24,78}, :103:20, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [134:0] _GEN_8 = {129'h0, _current_lg_len_req_T ? 3'h0 : usefulBytesRead, 3'h0};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :116:38, :126:52, generators/gemmini/src/main/scala/gemmini/Util.scala:109:8, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [3:0]   current_len_req = 4'h1 << (_current_lg_len_req_T ? io_req_bits_lg_len_req : req_bits_lg_len_req);	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :118:33, :119:32, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [3:0]   _bytesRead_T_2 = {1'h0, _current_lg_len_req_T ? 3'h0 : bytesRead} + 4'h1;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :51:22, :114:32, generators/gemmini/src/main/scala/gemmini/Util.scala:35:11, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire         _GEN_9 = bytesSent == req_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :50:22, :94:15]
  wire         _GEN_10 = _GEN_5 & _GEN_9;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:93:{19,59}, :94:15]
  wire         _GEN_11 = io_in_ready_0 & io_in_valid;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:66:30, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [2:0]   _rshift_T = {1'h0, _current_lg_len_req_T ? io_req_bits_shift : req_bits_shift} - (_current_lg_len_req_T ? 3'h0 : bytesRead - bytesReadAfterShift);	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16, :51:22, :52:32, :53:34, :115:37, :117:28, :121:25, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [7:0]   _GEN_12 = {2'h0, _rshift_T, 3'h0};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :121:25, :126:41]
  wire [134:0] _buffer_T_2 = {127'h0, io_in_bits >> _GEN_12} << _GEN_8;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:126:{41,52}, :128:{48,59}]
  wire [134:0] _mask_T_2 = {127'h0, 8'hFF >> _GEN_12} << _GEN_8;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:126:{41,52}]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
    req_valid <= ~(reset | _GEN_11 & ~_current_lg_len_req_T & _GEN_9 & _io_in_ready_T_1 - _GEN_0 < 4'h2) & (_current_lg_len_req_T | (_GEN_6 ? ~(_GEN_7 | _GEN_10) & req_valid : ~_GEN_10 & req_valid));	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16, :52:71, :62:{34,42,73}, :93:59, :94:{15,43}, :98:22, :101:{24,78}, :107:22, :113:21, :133:{11,24,64,81}, :138:23, :139:15, generators/gemmini/src/main/scala/gemmini/Util.scala:134:13, :139:13, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_current_lg_len_req_T) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      req_bits_shift <= io_req_bits_shift;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
      req_bits_addr <= io_req_bits_addr;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
      req_bits_is_acc <= io_req_bits_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
      req_bits_accumulate <= io_req_bits_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
      req_bits_has_acc_bitwidth <= io_req_bits_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
      req_bits_block_stride <= io_req_bits_block_stride;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
      req_bits_spad_row_offset <= io_req_bits_spad_row_offset;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
      req_bits_lg_len_req <= io_req_bits_lg_len_req;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
      req_bits_bytes_to_read <= io_req_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:43:16]
      bytesSent <= 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :50:22]
    end
    else if (_GEN_6)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      bytesSent <= bytesSent_next[2:0];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:50:22, :99:15, generators/gemmini/src/main/scala/gemmini/Util.scala:35:8]
    if (_GEN_11 & _rshift_T < 3'h2)	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :46:19, :113:21, :121:{25,50}, :123:7, :128:14, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      buffer <= ~(_mask_T_2[31:0]) & buffer | _buffer_T_2[31:0];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:46:19, :126:{19,52}, :128:{25,33,59}]
    if (_GEN_11)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      bytesRead <= _bytesRead_T_2 > current_len_req ? current_len_req[2:0] : _bytesRead_T_2[2:0];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:51:22, :119:32, generators/gemmini/src/main/scala/gemmini/Util.scala:35:{8,11,16,30}]
    else if (_current_lg_len_req_T)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      bytesRead <= 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :51:22]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
        req_valid = _RANDOM[3'h0][0];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        req_bits_shift = _RANDOM[3'h0][2:1];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        req_bits_addr = _RANDOM[3'h0][14:3];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        req_bits_is_acc = _RANDOM[3'h0][15];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        req_bits_accumulate = _RANDOM[3'h0][16];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        req_bits_has_acc_bitwidth = _RANDOM[3'h0][17];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        req_bits_block_stride = {_RANDOM[3'h2][31:26], _RANDOM[3'h3][9:0]};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        req_bits_spad_row_offset = _RANDOM[3'h3][14:10];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        req_bits_lg_len_req = _RANDOM[3'h3][16:15];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        req_bits_bytes_to_read = _RANDOM[3'h3][19:17];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
        buffer = {_RANDOM[3'h3][31:21], _RANDOM[3'h4][20:0]};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16, :46:19]
        bytesSent = _RANDOM[3'h4][23:21];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :46:19, :50:22]
        bytesRead = _RANDOM[3'h4][26:24];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :46:19, :51:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = io_req_ready_0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :64:16, :98:22, :101:78, :103:20]
  assign io_in_ready = io_in_ready_0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :66:30]
  assign io_out_valid = io_out_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :68:{29,60}]
  assign io_out_bits_data = _io_out_bits_data_T_5[31:0];	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :70:{20,53}]
  assign io_out_bits_addr = req_bits_addr + req_bits_block_stride[11:0] * {7'h0, req_bits_has_acc_bitwidth ? _io_out_bits_addr_total_bytes_sent_T / 5'h4 : _io_out_bits_addr_total_bytes_sent_T / 5'h2};	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16, :76:{37,61}, :77:53, :78:8, :82:84, :83:85]
  assign io_out_bits_is_acc = req_bits_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
  assign io_out_bits_accumulate = req_bits_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
  assign io_out_bits_has_acc_bitwidth = req_bits_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :43:16]
  assign io_out_bits_mask_0 = spad_row_offset == 5'h0 & (|({1'h0, spad_row_offset} + _GEN_2));	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :72:30, :73:{9,28}, :74:{11,29}]
  assign io_out_bits_mask_1 = spad_row_offset_1 < 5'h2 & (|(_GEN_3[5:1]));	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :72:30, :73:{9,28}, :74:{11,29}]
  assign io_out_bits_mask_2 = spad_row_offset_2 < 5'h3 & {1'h0, spad_row_offset_2} + _GEN_2 > 6'h2;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :72:30, :73:{9,28}, :74:{11,29}]
  assign io_out_bits_mask_3 = spad_row_offset_3 < 5'h4 & (|(_GEN_4[5:2]));	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :72:30, :73:{9,28}, :74:{11,29}]
  assign io_out_bits_last = last_sending;	// @[generators/gemmini/src/main/scala/gemmini/BeatMerger.scala:30:7, :61:37]
endmodule

