// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Mesh(	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
  input        clock,	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
  input  [2:0] io_in_id_0_0,	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:22:14]
  input  [2:0] io_in_id_1_0,	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:22:14]
  input        io_in_last_0_0,	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:22:14]
  input        io_in_last_1_0,	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:22:14]
  input        io_in_valid_0_0,	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:22:14]
  input        io_in_valid_1_0,	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:22:14]
  output       io_out_valid_0_0,	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:22:14]
  output [2:0] io_out_id_0_0,	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:22:14]
  output       io_out_last_0_0	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:22:14]
);

  wire [2:0] _mesh_1_0_io_out_id_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  wire       _mesh_1_0_io_out_last_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  wire       _mesh_1_0_io_out_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  wire [2:0] _mesh_0_1_io_out_id_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  wire       _mesh_0_1_io_out_last_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  wire       _mesh_0_1_io_out_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  wire [2:0] _mesh_0_0_io_out_id_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  wire       _mesh_0_0_io_out_last_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  wire       _mesh_0_0_io_out_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  reg        r_4_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
  reg        r_5_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
  reg        r_6_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
  reg        r_7_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
  reg  [2:0] r_8_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
  reg  [2:0] r_9_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
  reg  [2:0] r_10_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
  reg  [2:0] r_11_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
  reg        r_12_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
  reg        r_13_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
  reg        r_14_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
  reg        r_15_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
  reg        r_18_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:124:23]
  reg  [2:0] r_20_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:126:24]
  reg        r_21_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:127:26]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
    r_4_0 <= io_in_valid_0_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
    r_5_0 <= _mesh_0_0_io_out_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71, :94:42]
    r_6_0 <= io_in_valid_1_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
    r_7_0 <= _mesh_0_1_io_out_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71, :94:42]
    r_8_0 <= io_in_id_0_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
    r_9_0 <= _mesh_0_0_io_out_id_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71, :103:39]
    r_10_0 <= io_in_id_1_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
    r_11_0 <= _mesh_0_1_io_out_id_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71, :103:39]
    r_12_0 <= io_in_last_0_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
    r_13_0 <= _mesh_0_0_io_out_last_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71, :112:41]
    r_14_0 <= io_in_last_1_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
    r_15_0 <= _mesh_0_1_io_out_last_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71, :112:41]
    r_18_0 <= _mesh_1_0_io_out_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71, :124:23]
    r_20_0 <= _mesh_1_0_io_out_id_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71, :126:24]
    r_21_0 <= _mesh_1_0_io_out_last_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71, :127:26]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
        r_4_0 = _RANDOM[4'h5][28];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :94:42]
        r_5_0 = _RANDOM[4'h5][29];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :94:42]
        r_6_0 = _RANDOM[4'h5][30];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :94:42]
        r_7_0 = _RANDOM[4'h5][31];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :94:42]
        r_8_0 = _RANDOM[4'h6][2:0];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :103:39]
        r_9_0 = _RANDOM[4'h6][5:3];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :103:39]
        r_10_0 = _RANDOM[4'h6][8:6];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :103:39]
        r_11_0 = _RANDOM[4'h6][11:9];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :103:39]
        r_12_0 = _RANDOM[4'h6][12];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :103:39, :112:41]
        r_13_0 = _RANDOM[4'h6][13];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :103:39, :112:41]
        r_14_0 = _RANDOM[4'h6][14];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :103:39, :112:41]
        r_15_0 = _RANDOM[4'h6][15];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :103:39, :112:41]
        r_18_0 = _RANDOM[4'h7][24];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :124:23]
        r_20_0 = {_RANDOM[4'h7][31], _RANDOM[4'h8][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :124:23, :126:24]
        r_21_0 = _RANDOM[4'h8][2];	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :126:24, :127:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Tile mesh_0_0 (	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
    .io_in_id_0     (r_8_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
    .io_in_last_0   (r_12_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
    .io_out_id_0    (_mesh_0_0_io_out_id_0),
    .io_out_last_0  (_mesh_0_0_io_out_last_0),
    .io_in_valid_0  (r_4_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
    .io_out_valid_0 (_mesh_0_0_io_out_valid_0)
  );	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  Tile mesh_0_1 (	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
    .io_in_id_0     (r_10_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
    .io_in_last_0   (r_14_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
    .io_out_id_0    (_mesh_0_1_io_out_id_0),
    .io_out_last_0  (_mesh_0_1_io_out_last_0),
    .io_in_valid_0  (r_6_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
    .io_out_valid_0 (_mesh_0_1_io_out_valid_0)
  );	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  Tile mesh_1_0 (	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
    .io_in_id_0     (r_9_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
    .io_in_last_0   (r_13_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
    .io_out_id_0    (_mesh_1_0_io_out_id_0),
    .io_out_last_0  (_mesh_1_0_io_out_last_0),
    .io_in_valid_0  (r_5_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
    .io_out_valid_0 (_mesh_1_0_io_out_valid_0)
  );	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  Tile mesh_1_1 (	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
    .io_in_id_0     (r_11_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:103:39]
    .io_in_last_0   (r_15_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:112:41]
    .io_out_id_0    (/* unused */),
    .io_out_last_0  (/* unused */),
    .io_in_valid_0  (r_7_0),	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:94:42]
    .io_out_valid_0 (/* unused */)
  );	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:39:71]
  assign io_out_valid_0_0 = r_18_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :124:23]
  assign io_out_id_0_0 = r_20_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :126:24]
  assign io_out_last_0_0 = r_21_0;	// @[generators/gemmini/src/main/scala/gemmini/Mesh.scala:17:7, :127:26]
endmodule

