// Generated by CIRCT firtool-1.75.0
module PE_4(	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  input  [2:0] io_in_id,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output [2:0] io_out_id,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input        io_in_last,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output       io_out_last,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input        io_in_valid,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output       io_out_valid	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
);

  assign io_out_id = io_in_id;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  assign io_out_last = io_in_last;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  assign io_out_valid = io_in_valid;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
endmodule

