// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Pipeline_1(	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
  input        clock,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
  input        reset,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
  output       io_in_ready,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input        io_in_valid,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input        io_in_bits_resp_fromDMA,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input  [1:0] io_in_bits_resp_acc_bank_id,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  input        io_out_ready,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output       io_out_valid,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output       io_out_bits_resp_fromDMA,	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
  output [1:0] io_out_bits_resp_acc_bank_id	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:7:14]
);

  wire       stalling_6;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
  wire       stalling_5;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
  wire       stalling_4;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
  wire       stalling_3;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
  wire       stalling_2;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
  wire       stalling_1;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
  reg        stages_0_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg  [1:0] stages_0_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg        stages_1_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg  [1:0] stages_1_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg        stages_2_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg  [1:0] stages_2_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg        stages_3_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg  [1:0] stages_3_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg        stages_4_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg  [1:0] stages_4_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg        stages_5_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg  [1:0] stages_5_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg        stages_6_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg  [1:0] stages_6_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg        stages_7_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg  [1:0] stages_7_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
  reg        valids_0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
  reg        valids_1;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
  reg        valids_2;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
  reg        valids_3;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
  reg        valids_4;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
  reg        valids_5;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
  reg        valids_6;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
  reg        valids_7;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
  wire       stalling_7 = valids_7 & ~io_out_ready;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :28:{34,37}]
  wire       stalling_0 = valids_0 & stalling_1;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16]
  assign stalling_1 = valids_1 & stalling_2;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16]
  assign stalling_2 = valids_2 & stalling_3;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16]
  assign stalling_3 = valids_3 & stalling_4;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16]
  assign stalling_4 = valids_4 & stalling_5;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16]
  assign stalling_5 = valids_5 & stalling_6;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16]
  assign stalling_6 = valids_6 & stalling_7;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :28:34, :30:16]
  wire       _GEN = ~stalling_0 & io_in_valid;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:27:20, :30:16, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
    if (_GEN) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      stages_0_resp_fromDMA <= io_in_bits_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
      stages_0_resp_acc_bank_id <= io_in_bits_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
    end
    if (~stalling_1) begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
      stages_1_resp_fromDMA <= stages_0_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
      stages_1_resp_acc_bank_id <= stages_0_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
    end
    if (~stalling_2) begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
      stages_2_resp_fromDMA <= stages_1_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
      stages_2_resp_acc_bank_id <= stages_1_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
    end
    if (~stalling_3) begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
      stages_3_resp_fromDMA <= stages_2_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
      stages_3_resp_acc_bank_id <= stages_2_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
    end
    if (~stalling_4) begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
      stages_4_resp_fromDMA <= stages_3_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
      stages_4_resp_acc_bank_id <= stages_3_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
    end
    if (~stalling_5) begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
      stages_5_resp_fromDMA <= stages_4_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
      stages_5_resp_acc_bank_id <= stages_4_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
    end
    if (~stalling_6) begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:30:16]
      stages_6_resp_fromDMA <= stages_5_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
      stages_6_resp_acc_bank_id <= stages_5_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
    end
    if (~stalling_7) begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:28:34]
      stages_7_resp_fromDMA <= stages_6_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
      stages_7_resp_acc_bank_id <= stages_6_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:21:21]
    end
    if (reset) begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
      valids_0 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
      valids_1 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
      valids_2 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
      valids_3 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
      valids_4 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
      valids_5 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
      valids_6 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
      valids_7 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25]
    end
    else begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
      valids_0 <= _GEN | stalling_1 & valids_0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16, :40:17, :41:12, :45:22, :46:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      valids_1 <= valids_0 | stalling_2 & valids_1;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16, :40:17, :41:12, :49:16, :50:12]
      valids_2 <= valids_1 | stalling_3 & valids_2;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16, :40:17, :41:12, :49:16, :50:12]
      valids_3 <= valids_2 | stalling_4 & valids_3;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16, :40:17, :41:12, :49:16, :50:12]
      valids_4 <= valids_3 | stalling_5 & valids_4;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16, :40:17, :41:12, :49:16, :50:12]
      valids_5 <= valids_4 | stalling_6 & valids_5;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :30:16, :40:17, :41:12, :49:16, :50:12]
      valids_6 <= valids_5 | stalling_7 & valids_6;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :28:34, :40:17, :41:12, :49:16, :50:12]
      valids_7 <= valids_6 | ~io_out_ready & valids_7;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:22:25, :36:24, :37:19, :49:16, :50:12]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:41];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
        for (logic [5:0] i = 6'h0; i < 6'h2A; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
        stages_0_resp_fromDMA = _RANDOM[6'h1][0];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_0_resp_acc_bank_id = _RANDOM[6'h4][5:4];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_1_resp_fromDMA = _RANDOM[6'h6][6];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_1_resp_acc_bank_id = _RANDOM[6'h9][11:10];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_2_resp_fromDMA = _RANDOM[6'hB][12];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_2_resp_acc_bank_id = _RANDOM[6'hE][17:16];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_3_resp_fromDMA = _RANDOM[6'h10][18];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_3_resp_acc_bank_id = _RANDOM[6'h13][23:22];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_4_resp_fromDMA = _RANDOM[6'h15][24];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_4_resp_acc_bank_id = _RANDOM[6'h18][29:28];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_5_resp_fromDMA = _RANDOM[6'h1A][30];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_5_resp_acc_bank_id = _RANDOM[6'h1E][3:2];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_6_resp_fromDMA = _RANDOM[6'h20][4];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_6_resp_acc_bank_id = _RANDOM[6'h23][9:8];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_7_resp_fromDMA = _RANDOM[6'h25][10];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        stages_7_resp_acc_bank_id = _RANDOM[6'h28][15:14];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
        valids_0 = _RANDOM[6'h29][16];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :22:25]
        valids_1 = _RANDOM[6'h29][17];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :22:25]
        valids_2 = _RANDOM[6'h29][18];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :22:25]
        valids_3 = _RANDOM[6'h29][19];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :22:25]
        valids_4 = _RANDOM[6'h29][20];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :22:25]
        valids_5 = _RANDOM[6'h29][21];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :22:25]
        valids_6 = _RANDOM[6'h29][22];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :22:25]
        valids_7 = _RANDOM[6'h29][23];	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :22:25]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = ~stalling_0;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :27:20, :30:16]
  assign io_out_valid = valids_7;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :22:25]
  assign io_out_bits_resp_fromDMA = stages_7_resp_fromDMA;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
  assign io_out_bits_resp_acc_bank_id = stages_7_resp_acc_bank_id;	// @[generators/gemmini/src/main/scala/gemmini/Pipeline.scala:6:7, :21:21]
endmodule

