// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Queue1_GemminiCmd(	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input         clock,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input         reset,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  output        io_enq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [6:0]  io_enq_bits_cmd_inst_funct,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_cmd_inst_rs2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_cmd_inst_rs1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_inst_xd,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_inst_xs1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_inst_xs2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_cmd_inst_rd,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [6:0]  io_enq_bits_cmd_inst_opcode,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [63:0] io_enq_bits_cmd_rs1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [63:0] io_enq_bits_cmd_rs2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_debug,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_cease,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_wfi,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0] io_enq_bits_cmd_status_isa,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_cmd_status_dprv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_dv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_cmd_status_prv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_v,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_sd,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [22:0] io_enq_bits_cmd_status_zero2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_mpv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_gva,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_mbe,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_sbe,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_cmd_status_sxl,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_cmd_status_uxl,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_sd_rv32,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [7:0]  io_enq_bits_cmd_status_zero1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_tsr,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_tw,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_tvm,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_mxr,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_sum,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_mprv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_cmd_status_xs,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_cmd_status_fs,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_cmd_status_mpp,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_cmd_status_vs,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_spp,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_mpie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_ube,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_spie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_upie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_mie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_hie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_sie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_cmd_status_uie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_from_matmul_fsm,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_from_conv_fsm,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_deq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [6:0]  io_deq_bits_cmd_inst_funct,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [63:0] io_deq_bits_cmd_rs1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [63:0] io_deq_bits_cmd_rs2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_debug,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_cease,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_wfi,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0] io_deq_bits_cmd_status_isa,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_cmd_status_dprv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_dv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_cmd_status_prv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_v,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_sd,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [22:0] io_deq_bits_cmd_status_zero2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_mpv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_gva,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_mbe,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_sbe,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_cmd_status_sxl,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_cmd_status_uxl,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_sd_rv32,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [7:0]  io_deq_bits_cmd_status_zero1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_tsr,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_tw,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_tvm,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_mxr,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_sum,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_mprv,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_cmd_status_xs,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_cmd_status_fs,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_cmd_status_mpp,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_cmd_status_vs,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_spp,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_mpie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_ube,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_spie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_upie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_mie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_hie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_sie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_cmd_status_uie,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [2:0]  io_deq_bits_rob_id_bits	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
);

  reg  [270:0] ram;	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  reg          full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27]
  wire         do_enq = ~full & io_enq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :286:19]
  always @(posedge clock) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    if (do_enq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      ram <= {io_enq_bits_from_conv_fsm, io_enq_bits_from_matmul_fsm, 4'h9, io_enq_bits_cmd_status_uie, io_enq_bits_cmd_status_sie, io_enq_bits_cmd_status_hie, io_enq_bits_cmd_status_mie, io_enq_bits_cmd_status_upie, io_enq_bits_cmd_status_spie, io_enq_bits_cmd_status_ube, io_enq_bits_cmd_status_mpie, io_enq_bits_cmd_status_spp, io_enq_bits_cmd_status_vs, io_enq_bits_cmd_status_mpp, io_enq_bits_cmd_status_fs, io_enq_bits_cmd_status_xs, io_enq_bits_cmd_status_mprv, io_enq_bits_cmd_status_sum, io_enq_bits_cmd_status_mxr, io_enq_bits_cmd_status_tvm, io_enq_bits_cmd_status_tw, io_enq_bits_cmd_status_tsr, io_enq_bits_cmd_status_zero1, io_enq_bits_cmd_status_sd_rv32, io_enq_bits_cmd_status_uxl, io_enq_bits_cmd_status_sxl, io_enq_bits_cmd_status_sbe, io_enq_bits_cmd_status_mbe, io_enq_bits_cmd_status_gva, io_enq_bits_cmd_status_mpv, io_enq_bits_cmd_status_zero2, io_enq_bits_cmd_status_sd, io_enq_bits_cmd_status_v, io_enq_bits_cmd_status_prv, io_enq_bits_cmd_status_dv, io_enq_bits_cmd_status_dprv, io_enq_bits_cmd_status_isa, io_enq_bits_cmd_status_wfi, io_enq_bits_cmd_status_cease, io_enq_bits_cmd_status_debug, io_enq_bits_cmd_rs2, io_enq_bits_cmd_rs1, io_enq_bits_cmd_inst_opcode, io_enq_bits_cmd_inst_rd, io_enq_bits_cmd_inst_xs2, io_enq_bits_cmd_inst_xs1, io_enq_bits_cmd_inst_xd, io_enq_bits_cmd_inst_rs1, io_enq_bits_cmd_inst_rs2, io_enq_bits_cmd_inst_funct};	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
    if (reset)	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      full <= 1'h0;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27]
    else if (~(do_enq == (io_deq_ready & full)))	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16]
      full <= do_enq;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    initial begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        end	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        ram = {_RANDOM[4'h0][31:1], _RANDOM[4'h1], _RANDOM[4'h2], _RANDOM[4'h3], _RANDOM[4'h4], _RANDOM[4'h5], _RANDOM[4'h6], _RANDOM[4'h7], _RANDOM[4'h8][15:0]};	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
        full = _RANDOM[4'h0][0];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~full;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27, :286:19]
  assign io_deq_valid = full;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27]
  assign io_deq_bits_cmd_inst_funct = ram[6:0];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_rs1 = ram[95:32];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_rs2 = ram[159:96];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_debug = ram[160];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_cease = ram[161];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_wfi = ram[162];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_isa = ram[194:163];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_dprv = ram[196:195];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_dv = ram[197];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_prv = ram[199:198];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_v = ram[200];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_sd = ram[201];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_zero2 = ram[224:202];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_mpv = ram[225];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_gva = ram[226];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_mbe = ram[227];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_sbe = ram[228];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_sxl = ram[230:229];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_uxl = ram[232:231];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_sd_rv32 = ram[233];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_zero1 = ram[241:234];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_tsr = ram[242];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_tw = ram[243];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_tvm = ram[244];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_mxr = ram[245];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_sum = ram[246];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_mprv = ram[247];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_xs = ram[249:248];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_fs = ram[251:250];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_mpp = ram[253:252];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_vs = ram[255:254];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_spp = ram[256];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_mpie = ram[257];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_ube = ram[258];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_spie = ram[259];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_upie = ram[260];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_mie = ram[261];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_hie = ram[262];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_sie = ram[263];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cmd_status_uie = ram[264];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_rob_id_bits = ram[268:266];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
endmodule

