// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TagQueue(	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
  input        clock,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
  input        reset,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
  output       io_enq_ready,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  input        io_enq_valid,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  input        io_enq_bits_tag_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  input  [2:0] io_enq_bits_tag_rob_id_bits,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  input  [2:0] io_enq_bits_id,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  input        io_deq_ready,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output       io_deq_valid,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output       io_deq_bits_tag_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output [2:0] io_deq_bits_tag_rob_id_bits,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output [2:0] io_deq_bits_id,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output       io_all_0_tag_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output       io_all_1_tag_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output       io_all_2_tag_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output       io_all_3_tag_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output       io_all_4_tag_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
  output       io_all_5_tag_rob_id_valid	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:12:14]
);

  reg             regs_0_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_0_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_0_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg             regs_1_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_1_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_1_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg             regs_2_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_2_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_2_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg             regs_3_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_3_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_3_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg             regs_4_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_4_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_4_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg             regs_5_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_5_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      regs_5_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
  reg  [2:0]      raddr;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:19:22]
  reg  [2:0]      waddr;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:20:22]
  reg  [2:0]      len;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:21:20]
  wire            io_enq_ready_0 = len != 3'h6;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:21:20, :24:18, :26:19]
  wire [7:0]      _GEN = {{regs_0_tag_rob_id_valid}, {regs_0_tag_rob_id_valid}, {regs_5_tag_rob_id_valid}, {regs_4_tag_rob_id_valid}, {regs_3_tag_rob_id_valid}, {regs_2_tag_rob_id_valid}, {regs_1_tag_rob_id_valid}, {regs_0_tag_rob_id_valid}};	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :28:15]
  wire [7:0][2:0] _GEN_0 = {{regs_0_tag_rob_id_bits}, {regs_0_tag_rob_id_bits}, {regs_5_tag_rob_id_bits}, {regs_4_tag_rob_id_bits}, {regs_3_tag_rob_id_bits}, {regs_2_tag_rob_id_bits}, {regs_1_tag_rob_id_bits}, {regs_0_tag_rob_id_bits}};	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :28:15]
  wire [7:0][2:0] _GEN_1 = {{regs_0_id}, {regs_0_id}, {regs_5_id}, {regs_4_id}, {regs_3_id}, {regs_2_id}, {regs_1_id}, {regs_0_id}};	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :28:15]
  `ifndef SYNTHESIS	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:51:9]
    always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:51:9]
      if (~reset & (&len)) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:21:20, :51:{9,14}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:51:9]
          $error("Assertion failed\n    at TagQueue.scala:51 assert(len <= entries.U)\n");	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:51:9]
        if (`STOP_COND_)	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:51:9]
          $fatal;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:51:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire            _GEN_2 = io_enq_ready_0 & io_enq_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:24:18, :26:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire            _GEN_3 = _GEN_2 & waddr == 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :20:22, :31:22, :32:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire            _GEN_4 = _GEN_2 & waddr == 3'h1;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :20:22, :31:22, :32:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire            _GEN_5 = _GEN_2 & waddr == 3'h2;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :20:22, :31:22, :32:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire            _GEN_6 = _GEN_2 & waddr == 3'h3;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :20:22, :31:22, :32:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire            _GEN_7 = _GEN_2 & waddr == 3'h4;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :20:22, :31:22, :32:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire            _GEN_8 = _GEN_2 & waddr == 3'h5;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :20:22, :31:22, :32:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire            _GEN_9 = io_deq_ready & (|len);	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:21:20, :23:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
    regs_0_tag_rob_id_valid <= ~(reset | _GEN_9 & raddr == 3'h0) & (_GEN_3 ? io_enq_bits_tag_rob_id_valid : regs_0_tag_rob_id_valid);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:59:20, generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :19:22, :31:22, :32:17, :36:22, :47:23, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_3) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :31:22, :32:17]
      regs_0_tag_rob_id_bits <= io_enq_bits_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
      regs_0_id <= io_enq_bits_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
    end
    regs_1_tag_rob_id_valid <= ~(reset | _GEN_9 & raddr == 3'h1) & (_GEN_4 ? io_enq_bits_tag_rob_id_valid : regs_1_tag_rob_id_valid);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:59:20, generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :19:22, :31:22, :32:17, :36:22, :47:23, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_4) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :31:22, :32:17]
      regs_1_tag_rob_id_bits <= io_enq_bits_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
      regs_1_id <= io_enq_bits_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
    end
    regs_2_tag_rob_id_valid <= ~(reset | _GEN_9 & raddr == 3'h2) & (_GEN_5 ? io_enq_bits_tag_rob_id_valid : regs_2_tag_rob_id_valid);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:59:20, generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :19:22, :31:22, :32:17, :36:22, :47:23, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_5) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :31:22, :32:17]
      regs_2_tag_rob_id_bits <= io_enq_bits_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
      regs_2_id <= io_enq_bits_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
    end
    regs_3_tag_rob_id_valid <= ~(reset | _GEN_9 & raddr == 3'h3) & (_GEN_6 ? io_enq_bits_tag_rob_id_valid : regs_3_tag_rob_id_valid);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:59:20, generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :19:22, :31:22, :32:17, :36:22, :47:23, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_6) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :31:22, :32:17]
      regs_3_tag_rob_id_bits <= io_enq_bits_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
      regs_3_id <= io_enq_bits_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
    end
    regs_4_tag_rob_id_valid <= ~(reset | _GEN_9 & raddr == 3'h4) & (_GEN_7 ? io_enq_bits_tag_rob_id_valid : regs_4_tag_rob_id_valid);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:59:20, generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :19:22, :31:22, :32:17, :36:22, :47:23, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_7) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :31:22, :32:17]
      regs_4_tag_rob_id_bits <= io_enq_bits_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
      regs_4_id <= io_enq_bits_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
    end
    regs_5_tag_rob_id_valid <= ~(reset | _GEN_9 & raddr == 3'h5) & (_GEN_8 ? io_enq_bits_tag_rob_id_valid : regs_5_tag_rob_id_valid);	// @[generators/gemmini/src/main/scala/gemmini/ExecuteController.scala:59:20, generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :19:22, :31:22, :32:17, :36:22, :47:23, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_8) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17, :31:22, :32:17]
      regs_5_tag_rob_id_bits <= io_enq_bits_tag_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
      regs_5_id <= io_enq_bits_id;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:18:17]
    end
    if (reset) begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
      raddr <= 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:19:22]
      waddr <= 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:20:22]
      len <= 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:21:20]
    end
    else begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
      if (_GEN_9)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        raddr <= raddr > 3'h4 ? 3'h1 - (3'h5 - raddr) - 3'h1 : raddr + 3'h1;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:19:22, generators/gemmini/src/main/scala/gemmini/Util.scala:13:{10,13,48,57,62,71}]
      if (_GEN_2)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        waddr <= waddr > 3'h4 ? 3'h1 - (3'h5 - waddr) - 3'h1 : waddr + 3'h1;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:20:22, generators/gemmini/src/main/scala/gemmini/Util.scala:13:{10,13,48,57,62,71}]
      if (_GEN_2 & ~_GEN_9)	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:41:{21,24}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        len <= len + 3'h1;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:21:20, :42:16]
      else if (~_GEN_2 & _GEN_9)	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:43:{14,27}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        len <= len - 3'h1;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:21:20, :44:16]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
        regs_0_tag_rob_id_valid = _RANDOM[4'h0][0];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_0_tag_rob_id_bits = _RANDOM[4'h0][3:1];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_0_id = _RANDOM[4'h1][10:8];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_1_tag_rob_id_valid = _RANDOM[4'h1][13];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_1_tag_rob_id_bits = _RANDOM[4'h1][16:14];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_1_id = _RANDOM[4'h2][23:21];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_2_tag_rob_id_valid = _RANDOM[4'h2][26];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_2_tag_rob_id_bits = _RANDOM[4'h2][29:27];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_2_id = _RANDOM[4'h4][4:2];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_3_tag_rob_id_valid = _RANDOM[4'h4][7];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_3_tag_rob_id_bits = _RANDOM[4'h4][10:8];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_3_id = _RANDOM[4'h5][17:15];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_4_tag_rob_id_valid = _RANDOM[4'h5][20];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_4_tag_rob_id_bits = _RANDOM[4'h5][23:21];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_4_id = _RANDOM[4'h6][30:28];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_5_tag_rob_id_valid = _RANDOM[4'h7][1];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_5_tag_rob_id_bits = _RANDOM[4'h7][4:2];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        regs_5_id = _RANDOM[4'h8][11:9];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
        raddr = _RANDOM[4'h8][16:14];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17, :19:22]
        waddr = _RANDOM[4'h8][19:17];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17, :20:22]
        len = _RANDOM[4'h8][22:20];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17, :21:20]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = io_enq_ready_0;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :24:18, :26:19]
  assign io_deq_valid = |len;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :21:20, :23:19]
  assign io_deq_bits_tag_rob_id_valid = _GEN[raddr];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :19:22, :28:15]
  assign io_deq_bits_tag_rob_id_bits = _GEN_0[raddr];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :19:22, :28:15]
  assign io_deq_bits_id = _GEN_1[raddr];	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :19:22, :28:15]
  assign io_all_0_tag_rob_id_valid = regs_0_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
  assign io_all_1_tag_rob_id_valid = regs_1_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
  assign io_all_2_tag_rob_id_valid = regs_2_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
  assign io_all_3_tag_rob_id_valid = regs_3_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
  assign io_all_4_tag_rob_id_valid = regs_4_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
  assign io_all_5_tag_rob_id_valid = regs_5_tag_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/TagQueue.scala:11:7, :18:17]
endmodule

