// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module TwoPortSyncMem(	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:30:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:30:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:30:7]
  input  [7:0]  io_waddr,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  input  [7:0]  io_raddr,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  input  [15:0] io_wdata_0_0,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  input  [15:0] io_wdata_1_0,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  output [15:0] io_rdata_0_0,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  output [15:0] io_rdata_1_0,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  input         io_wen,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  input         io_ren,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  input         io_mask_0,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  input         io_mask_1,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  input         io_mask_2,	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
  input         io_mask_3	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:31:14]
);

  wire [31:0] _mem_R0_data;	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:45:24]
  `ifndef SYNTHESIS	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:41:9]
    always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:41:9]
      if (~reset & io_wen & io_ren & io_raddr == io_waddr) begin	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:41:{9,19,29,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:41:9]
          $error("Assertion failed: undefined behavior in dual-ported SRAM\n    at SyncMem.scala:41 assert(!(io.wen && io.ren && io.raddr === io.waddr), \"undefined behavior in dual-ported SRAM\")\n");	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:41:9]
        if (`STOP_COND_)	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:41:9]
          $fatal;	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:41:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  mem_0 mem (	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:45:24]
    .R0_addr (io_raddr),
    .R0_en   (io_ren),
    .R0_clk  (clock),
    .R0_data (_mem_R0_data),
    .W0_addr (io_waddr),
    .W0_en   (io_wen),
    .W0_clk  (clock),
    .W0_data ({io_wdata_1_0, io_wdata_0_0}),	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:50:42]
    .W0_mask ({io_mask_3, io_mask_2, io_mask_1, io_mask_0})	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:45:24]
  );	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:45:24]
  assign io_rdata_0_0 = _mem_R0_data[15:0];	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:30:7, :45:24, :47:50]
  assign io_rdata_1_0 = _mem_R0_data[31:16];	// @[generators/gemmini/src/main/scala/gemmini/SyncMem.scala:30:7, :45:24, :47:50]
endmodule

