// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module VectorScalarMultiplier_1(	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
  output        io_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [15:0] io_req_bits_in_0,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [15:0] io_req_bits_in_1,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [15:0] io_req_bits_repeats,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_bits_last,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [11:0] io_req_bits_tag_addr,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_bits_tag_mask_0,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_bits_tag_mask_1,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_bits_tag_mask_2,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_bits_tag_mask_3,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_bits_tag_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_req_bits_tag_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [7:0]  io_req_bits_tag_bytes_read,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input  [7:0]  io_req_bits_tag_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  input         io_resp_ready,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_valid,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [15:0] io_resp_bits_out_0,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [15:0] io_resp_bits_out_1,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [15:0] io_resp_bits_row,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_bits_last,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [11:0] io_resp_bits_tag_addr,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_bits_tag_mask_0,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_bits_tag_mask_1,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_bits_tag_mask_2,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_bits_tag_mask_3,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_bits_tag_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output        io_resp_bits_tag_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [7:0]  io_resp_bits_tag_bytes_read,	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
  output [7:0]  io_resp_bits_tag_cmd_id	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:54:14]
);

  wire        in_fire;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _pipe_io_in_ready;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:83:22]
  reg         in_valid;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [15:0] in_bits_in_0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [15:0] in_bits_in_1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [15:0] in_bits_repeats;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_last;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [11:0] in_bits_tag_addr;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_2;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_mask_3;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg         in_bits_tag_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [7:0]  in_bits_tag_bytes_read;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  reg  [7:0]  in_bits_tag_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
  wire        _pipe_io_in_bits_last_T = in_bits_repeats == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :67:49]
  wire        io_req_ready_0 = ~in_valid | _pipe_io_in_bits_last_T & in_fire;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :67:{19,29,49,57}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign in_fire = _pipe_io_in_ready & in_valid;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :83:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN = io_req_ready_0 & io_req_valid;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:67:29, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
    if (reset)	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
      in_valid <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    else	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
      in_valid <= _GEN ? io_req_valid : ~(in_fire & _pipe_io_in_bits_last_T) & in_valid;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :67:49, :69:22, :70:14, :72:25, :73:36, :74:16, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      in_bits_in_0 <= io_req_bits_in_0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_in_1 <= io_req_bits_in_1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_repeats <= io_req_bits_repeats;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_last <= io_req_bits_last;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_addr <= io_req_bits_tag_addr;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_0 <= io_req_bits_tag_mask_0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_1 <= io_req_bits_tag_mask_1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_2 <= io_req_bits_tag_mask_2;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_mask_3 <= io_req_bits_tag_mask_3;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_is_acc <= io_req_bits_tag_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_accumulate <= io_req_bits_tag_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_bytes_read <= io_req_bits_tag_bytes_read;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
      in_bits_tag_cmd_id <= io_req_bits_tag_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    end
    else if (in_fire)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      in_bits_repeats <= in_bits_repeats - 16'h1;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :76:40]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
        in_valid = _RANDOM[3'h0][0];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_in_0 = _RANDOM[3'h0][16:1];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_in_1 = {_RANDOM[3'h0][31:17], _RANDOM[3'h1][0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_repeats = _RANDOM[3'h1][17:2];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_last = _RANDOM[3'h1][26];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_tag_addr = {_RANDOM[3'h2][31:27], _RANDOM[3'h3][6:0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_tag_mask_0 = _RANDOM[3'h3][7];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_tag_mask_1 = _RANDOM[3'h3][8];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_tag_mask_2 = _RANDOM[3'h3][9];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_tag_mask_3 = _RANDOM[3'h3][10];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_tag_is_acc = _RANDOM[3'h3][11];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_tag_accumulate = _RANDOM[3'h3][12];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_tag_bytes_read = {_RANDOM[3'h5][31], _RANDOM[3'h6][6:0]};	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
        in_bits_tag_cmd_id = _RANDOM[3'h6][14:7];	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :65:15]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Pipeline pipe (	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:83:22]
    .io_in_ready                (_pipe_io_in_ready),
    .io_in_valid                (in_valid),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_0           (in_bits_in_0),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_out_1           (in_bits_in_1),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_row             (in_bits_repeats),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_last            (_pipe_io_in_bits_last_T & in_bits_last),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15, :67:49, :92:53]
    .io_in_bits_tag_addr        (in_bits_tag_addr),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_0      (in_bits_tag_mask_0),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_1      (in_bits_tag_mask_1),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_2      (in_bits_tag_mask_2),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_mask_3      (in_bits_tag_mask_3),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_is_acc      (in_bits_tag_is_acc),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_accumulate  (in_bits_tag_accumulate),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_bytes_read  (in_bits_tag_bytes_read),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_in_bits_tag_cmd_id      (in_bits_tag_cmd_id),	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:65:15]
    .io_out_ready               (io_resp_ready),
    .io_out_valid               (io_resp_valid),
    .io_out_bits_out_0          (io_resp_bits_out_0),
    .io_out_bits_out_1          (io_resp_bits_out_1),
    .io_out_bits_row            (io_resp_bits_row),
    .io_out_bits_last           (io_resp_bits_last),
    .io_out_bits_tag_addr       (io_resp_bits_tag_addr),
    .io_out_bits_tag_mask_0     (io_resp_bits_tag_mask_0),
    .io_out_bits_tag_mask_1     (io_resp_bits_tag_mask_1),
    .io_out_bits_tag_mask_2     (io_resp_bits_tag_mask_2),
    .io_out_bits_tag_mask_3     (io_resp_bits_tag_mask_3),
    .io_out_bits_tag_is_acc     (io_resp_bits_tag_is_acc),
    .io_out_bits_tag_accumulate (io_resp_bits_tag_accumulate),
    .io_out_bits_tag_bytes_read (io_resp_bits_tag_bytes_read),
    .io_out_bits_tag_cmd_id     (io_resp_bits_tag_cmd_id)
  );	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:83:22]
  assign io_req_ready = io_req_ready_0;	// @[generators/gemmini/src/main/scala/gemmini/VectorScalarMultiplier.scala:45:7, :67:29]
endmodule

