// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module XactTracker(	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
  input         io_alloc_valid,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output        io_alloc_ready,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output        io_alloc_xactid,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input  [1:0]  io_alloc_entry_shift,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input  [11:0] io_alloc_entry_addr,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input         io_alloc_entry_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input         io_alloc_entry_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input         io_alloc_entry_has_acc_bitwidth,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input  [31:0] io_alloc_entry_scale,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input  [15:0] io_alloc_entry_repeats,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input  [7:0]  io_alloc_entry_pixel_repeats,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input  [15:0] io_alloc_entry_len,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input  [15:0] io_alloc_entry_block_stride,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input  [4:0]  io_alloc_entry_spad_row_offset,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input  [2:0]  io_alloc_entry_bytes_to_read,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input         io_alloc_entry_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input         io_peek_xactid,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  input         io_peek_pop,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output [1:0]  io_peek_entry_shift,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output [11:0] io_peek_entry_addr,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output        io_peek_entry_is_acc,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output        io_peek_entry_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output        io_peek_entry_has_acc_bitwidth,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output [31:0] io_peek_entry_scale,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output [15:0] io_peek_entry_repeats,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output [7:0]  io_peek_entry_pixel_repeats,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output [15:0] io_peek_entry_len,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output [15:0] io_peek_entry_block_stride,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output [4:0]  io_peek_entry_spad_row_offset,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output [2:0]  io_peek_entry_bytes_to_read,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output        io_peek_entry_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
  output        io_busy	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:59:14]
);

  reg         free_entry;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [1:0]  entries_0_bits_shift;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [11:0] entries_0_bits_addr;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg         entries_0_bits_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg         entries_0_bits_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg         entries_0_bits_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [31:0] entries_0_bits_scale;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [15:0] entries_0_bits_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [7:0]  entries_0_bits_pixel_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [15:0] entries_0_bits_len;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [15:0] entries_0_bits_block_stride;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [4:0]  entries_0_bits_spad_row_offset;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [2:0]  entries_0_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg         entries_0_bits_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg         entries_1_valid;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [1:0]  entries_1_bits_shift;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [11:0] entries_1_bits_addr;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg         entries_1_bits_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg         entries_1_bits_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg         entries_1_bits_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [31:0] entries_1_bits_scale;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [15:0] entries_1_bits_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [7:0]  entries_1_bits_pixel_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [15:0] entries_1_bits_len;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [15:0] entries_1_bits_block_stride;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [4:0]  entries_1_bits_spad_row_offset;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg  [2:0]  entries_1_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  reg         entries_1_bits_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
  wire        _io_alloc_ready_T = free_entry & entries_1_valid;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20, :70:52]
  wire        _GEN = io_peek_xactid ? entries_1_valid : free_entry;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20, :73:17]
  wire        _GEN_0 = io_peek_pop & ~reset;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:84:11]
  `ifndef SYNTHESIS	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:84:11]
    always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:84:11]
      if (_GEN_0 & ~_GEN) begin	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:73:17, :84:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:84:11]
          $error("Assertion failed\n    at XactTracker.scala:84 assert(entries(io.peek.xactid).valid)\n");	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:84:11]
        if (`STOP_COND_)	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:84:11]
          $fatal;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:84:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _GEN_1 = io_alloc_valid & ~_io_alloc_ready_T;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:36:36, :70:{21,52}]
  wire        _GEN_2 = _GEN_1 & ~free_entry;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire        _GEN_3 = _GEN_1 & free_entry;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
    if (_GEN_0)	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:84:11]
      assert__assert: assert(_GEN);	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:73:17, :84:11]
    free_entry <= ~(reset | io_peek_pop & ~io_peek_xactid) & (_GEN_2 | free_entry);	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_2) begin	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20, :77:26, :78:31]
      entries_0_bits_shift <= io_alloc_entry_shift;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_addr <= io_alloc_entry_addr;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_is_acc <= io_alloc_entry_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_accumulate <= io_alloc_entry_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_scale <= io_alloc_entry_scale;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_repeats <= io_alloc_entry_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_len <= io_alloc_entry_len;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_block_stride <= io_alloc_entry_block_stride;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_0_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
    end
    entries_1_valid <= ~(reset | io_peek_pop & io_peek_xactid) & (_GEN_3 | entries_1_valid);	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_3) begin	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20, :77:26, :78:31]
      entries_1_bits_shift <= io_alloc_entry_shift;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_addr <= io_alloc_entry_addr;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_is_acc <= io_alloc_entry_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_accumulate <= io_alloc_entry_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_scale <= io_alloc_entry_scale;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_repeats <= io_alloc_entry_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_len <= io_alloc_entry_len;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_block_stride <= io_alloc_entry_block_stride;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
      entries_1_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:67:20]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:7];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
        free_entry = _RANDOM[3'h0][0];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_shift = _RANDOM[3'h0][2:1];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_addr = _RANDOM[3'h0][14:3];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_is_acc = _RANDOM[3'h0][15];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_accumulate = _RANDOM[3'h0][16];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_has_acc_bitwidth = _RANDOM[3'h0][17];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_scale = {_RANDOM[3'h0][31:18], _RANDOM[3'h1][17:0]};	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_repeats = {_RANDOM[3'h1][31:18], _RANDOM[3'h2][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_pixel_repeats = _RANDOM[3'h2][9:2];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_len = _RANDOM[3'h2][25:10];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_block_stride = {_RANDOM[3'h2][31:26], _RANDOM[3'h3][9:0]};	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_spad_row_offset = _RANDOM[3'h3][14:10];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_bytes_to_read = _RANDOM[3'h3][19:17];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_0_bits_cmd_id = _RANDOM[3'h3][20];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_valid = _RANDOM[3'h3][21];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_shift = _RANDOM[3'h3][23:22];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_addr = {_RANDOM[3'h3][31:24], _RANDOM[3'h4][3:0]};	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_is_acc = _RANDOM[3'h4][4];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_accumulate = _RANDOM[3'h4][5];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_has_acc_bitwidth = _RANDOM[3'h4][6];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_scale = {_RANDOM[3'h4][31:7], _RANDOM[3'h5][6:0]};	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_repeats = _RANDOM[3'h5][22:7];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_pixel_repeats = _RANDOM[3'h5][30:23];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_len = {_RANDOM[3'h5][31], _RANDOM[3'h6][14:0]};	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_block_stride = _RANDOM[3'h6][30:15];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_spad_row_offset = {_RANDOM[3'h6][31], _RANDOM[3'h7][3:0]};	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_bytes_to_read = _RANDOM[3'h7][8:6];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
        entries_1_bits_cmd_id = _RANDOM[3'h7][9];	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_alloc_ready = ~_io_alloc_ready_T;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :70:{21,52}]
  assign io_alloc_xactid = free_entry;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20]
  assign io_peek_entry_shift = io_peek_xactid ? entries_1_bits_shift : entries_0_bits_shift;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_addr = io_peek_xactid ? entries_1_bits_addr : entries_0_bits_addr;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_is_acc = io_peek_xactid ? entries_1_bits_is_acc : entries_0_bits_is_acc;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_accumulate = io_peek_xactid ? entries_1_bits_accumulate : entries_0_bits_accumulate;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_has_acc_bitwidth = io_peek_xactid ? entries_1_bits_has_acc_bitwidth : entries_0_bits_has_acc_bitwidth;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_scale = io_peek_xactid ? entries_1_bits_scale : entries_0_bits_scale;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_repeats = io_peek_xactid ? entries_1_bits_repeats : entries_0_bits_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_pixel_repeats = io_peek_xactid ? entries_1_bits_pixel_repeats : entries_0_bits_pixel_repeats;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_len = io_peek_xactid ? entries_1_bits_len : entries_0_bits_len;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_block_stride = io_peek_xactid ? entries_1_bits_block_stride : entries_0_bits_block_stride;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_spad_row_offset = io_peek_xactid ? entries_1_bits_spad_row_offset : entries_0_bits_spad_row_offset;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_bytes_to_read = io_peek_xactid ? entries_1_bits_bytes_to_read : entries_0_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_peek_entry_cmd_id = io_peek_xactid ? entries_1_bits_cmd_id : entries_0_bits_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :73:17]
  assign io_busy = free_entry | entries_1_valid;	// @[generators/gemmini/src/main/scala/gemmini/XactTracker.scala:56:7, :67:20, :75:44]
endmodule

